# -*- coding: utf-8 -*-
"""Rune, affissi, razze e nomi delle passive.

I nomi delle passive compaiono anche fra le etichette di Attributes: una
traduzione copre entrambe le categorie.

Cornici escluse di proposito: '{{n0}} {t0} {t1}' (19 righe) mescola due strutture
inglesi che in italiano divergono -- "Blunt Armor" e' "Armatura contundente"
(aggettivo) ma "Decay Piercing" e' "Penetrazione da decadimento" (complemento).
Quelle righe restano scoperte invece di uscire sbagliate a meta'.
"""

# cornici delle righe di statistica. {{n0}} rende la graffa letterale: la
# stringa del gioco contiene "{0}", che a runtime diventa il valore numerico.
# Nel lato italiano servono TRE graffe: in str.format "{{n0}}" produce il
# testo letterale "{n0}", mentre "{{{n0}}}" produce "{" + valore + "}".
ATTR_FRAMES = {
    "{{n0}} {t0}": "{{{n0}}} {t0}",
    "{{n0}}% {t0}": "{{{n0}}}% {t0}",
    "% {t0}": "% {t0}",
    "{{n0}} Max {t0}": "{{{n0}}} {t0} max",
    "% {t0} vs. {t1}": "% {t0} vs. {adj1}",
    "{{n0}}% {t0} vs. {t1}": "{{{n0}}}% {t0} vs. {adj1}",
    "% Damage vs. {t0}": "% Danno vs. {adj0}",
    "{{n0}}% Damage vs. {t0}": "{{{n0}}}% Danno vs. {adj0}",
    "% {t0} Damage": "% Danno da {t0}",
    "{{n0}}% {t0} Damage": "{{{n0}}}% Danno da {t0}",
    "{{n0}} {t0} Regen": "{{{n0}}} Rigen. {t0}",
    "{t0} Up": "Aumento di {t0}",
    "{t0} Down": "Riduzione di {t0}",
    "{t0} is increased.": "{art0} {t0} aumenta.",
    "{t0} is reduced.": "{art0} {t0} si riduce.",
}

ATTR = {
    # ---- affissi delle rune ------------------------------------------------
    "Aetheric": "Eterico",
    "Alacrity": "Alacrità",
    "Bolstering": "Rinforzante",
    "Charged": "Carico",
    "Commanding": "Imperioso",
    "Cracking": "Spaccante",
    "Deadly": "Letale",
    "Enduring": "Resistente",
    "Flaming": "Fiammeggiante",
    "Focused": "Focalizzato",
    "Frosted": "Gelido",
    "Hasty": "Affrettato",
    "Hearty": "Vigoroso",
    "Lightweight": "Leggero",
    "Meditative": "Meditativo",
    "Mending": "Risanante",
    "Phasing": "Sfasato",
    "Quick": "Rapido",
    "Replenishing": "Ristoratore",
    "Restorative": "Rigenerante",
    "Rooted": "Radicato",
    "Rotting": "Putrescente",
    "Ruthless": "Spietato",
    "Savage": "Selvaggio",
    "Scorching": "Bruciante",
    "Sharp": "Affilato",
    "Shocking": "Folgorante",
    "Slicing": "Tagliente",
    "Smashing": "Fracassante",
    "Solid": "Solido",
    # 'Splitting' non puo' essere "Fendente": quello e' gia' 'Cleave'
    "Splitting": "Scindente",
    "Stalwart": "Saldo",
    "Sundering": "Squassante",
    "Swift": "Veloce",
    "Toxic": "Tossico",
    "Unraveling": "Disfacente",
    "Wardbound": "Legato alla Guardia",
    "Withering": "Avvizzente",
    "Heal": "Cura",
    "Ice": "Ghiaccio",
    "HP": "HP",

    # ---- razze e creature --------------------------------------------------
    "Centaur": "Centauro",
    "Dwarf": "Nano",
    "Fairy": "Fata",
    "Golem": "Golem",
    "Griffon": "Grifone",
    "Shaman": "Sciamano",
    "Troll": "Troll",
    "Mystic": "Mistico",

    # ---- etichette varie ---------------------------------------------------
    "Build Unlock": "Sblocco costruzione",
    "Recipe Unlock": "Sblocco ricetta",
    "Spell Unlock": "Sblocco incantesimo",
    "Tool Level": "Livello strumento",
    "Requires Level": "Richiede livello",
    "Flaming Oil Coating": "Rivestimento di Olio Fiammeggiante",
    "Frosted Oil Coating": "Rivestimento di Olio Gelido",
    "Toxic Oil Coating": "Rivestimento di Olio Tossico",
    "Versatile Warrior": "Guerriero Versatile",
    "for": "per",
    "Increase attack speed": "Aumenta la velocità d'attacco",
    "Increase movement speed": "Aumenta la velocità di movimento",
    "Increases Ice Resistance": "Aumenta la resistenza al ghiaccio",

    # ---- nomi delle passive (valgono anche per Attributes) ----------------
    "Accelerated Casting": "Lancio Accelerato",
    "Ambush": "Imboscata",
    "Arcane Endurance": "Resistenza Arcana",
    "Arrow Of The Deep Cold": "Freccia del Freddo Profondo",
    "Ashen Escalation": "Escalation di Cenere",
    "Beastfury": "Furia Ferina",
    "Blackblood Tempo": "Tempo di Sangue Nero",
    "Blazeborne Daggers": "Pugnali Nati dalla Fiamma",
    "Blazing Wrath": "Ira Ardente",
    "Blood In The Water": "Sangue nell'Acqua",
    "Blood in the Water": "Sangue nell'Acqua",
    "Bloodfrenzy": "Frenesia Sanguinaria",
    "Blunt Force Execute": "Esecuzione Contundente",
    "Bone Breaker": "Spaccaossa",
    "Bulwark": "Baluardo",
    "Call To The Moon": "Richiamo alla Luna",
    "Calmdrift": "Deriva Calma",
    "Channeled Call": "Richiamo Canalizzato",
    "Cinder Detonation": "Detonazione di Brace",
    "Cold Scaled Power": "Potere Scalato dal Freddo",
    "Cold-Scaled Power": "Potere Scalato dal Freddo",
    "Counterfire Discipline": "Disciplina del Controfuoco",
    "Dashburst": "Scatto Esplosivo",
    "Deadly Rhythm": "Ritmo Letale",
    "Deeprest": "Riposo Profondo",
    "Defend And Assault": "Difesa e Assalto",
    "Defend and Assault": "Difesa e Assalto",
    "Dualbond": "Doppio Vincolo",
    "Dualpath": "Doppia Via",
    "Echo Shade": "Ombra d'Eco",
    "Echo Weaver": "Tessitore d'Eco",
    "Echoed Focus": "Concentrazione Riecheggiata",
    "Echoes Of Ice": "Echi di Ghiaccio",
    "Echoes of Ice": "Echi di Ghiaccio",
    "Elvish Velocity": "Velocità Elfica",
    "Ember Cascade": "Cascata di Brace",
    "Emberlash": "Sferzata di Brace",
    "Enraging Parry": "Parata Infuriante",
    "Festering Wounds": "Ferite Purulente",
    "Finishing Edge": "Filo Finale",
    "Flamefeed Frenzy": "Frenesia Nutrifiamma",
    "Focused Assault": "Assalto Focalizzato",
    "Frost Forged Might": "Possanza Forgiata dal Gelo",
    "Frostbite Focus": "Concentrazione del Congelamento",
    "Frostborne Daggers": "Pugnali Nati dal Gelo",
    "Frostquake": "Sisma Gelido",
    "Frostshock": "Scossa Gelida",
    "Glacial Drag": "Trascinamento Glaciale",
    "Gloom Stalker": "Cacciatore dell'Ombra",
    "Gorewraith Ambush": "Imboscata dello Spettro Cruento",
    "Guardstep": "Passo Guardiano",
    "Haymaker": "Colpo Demolitore",
    "Infection Scent": "Odore d'Infezione",
    "Infectious Cleaver": "Mannaia Infettiva",
    "Kindled Focus": "Concentrazione Ravvivata",
    "Knockout Reserves": "Riserve da Knockout",
    "Lionsurge": "Ondata del Leone",
    "Many Cut Phantom": "Fantasma dai Molti Tagli",
    "Murder Tempo": "Tempo Omicida",
    "Mystweave": "Trama Mistica",
    "Nerveblight": "Piaga Nervosa",
    "Nights Whisper": "Sussurro della Notte",
    "Overchannel": "Sovraccanalizzazione",
    "Packbond": "Vincolo del Branco",
    "Pathsurge": "Ondata di Sentieri",
    "Permafrost Rhythm": "Ritmo del Permafrost",
    "Pestilent Tremor": "Tremore Pestilenziale",
    "Phantom Crossfire": "Fuoco Incrociato Fantasma",
    "Phase Duellist": "Duellante di Fase",
    "Plague Marksmanship": "Tiro della Peste",
    "Plague Mind": "Mente della Peste",
    "Pulverizing Frenzy": "Frenesia Polverizzante",
    "Pummel": "Martellamento",
    "Pyre Echo": "Eco della Pira",
    "Quicktrade": "Scambio Rapido",
    "Rage From Ruin": "Furia dalla Rovina",
    "Rage from Ruin": "Furia dalla Rovina",
    "Recoverative Rage": "Furia Recuperativa",
    "Recovering Finisher": "Finisher Ristoratore",
    "Regenerative Rage": "Furia Rigenerativa",
    "Rejuvenating Rage": "Furia Ringiovanente",
    "Riposte": "Riposta",
    "Riposte Discipline": "Disciplina della Riposta",
    "Rippling Echoes": "Echi Ondeggianti",
    "Riptide": "Marea Impetuosa",
    "Rootfan": "Ventaglio di Radici",
    "Second Wind": "Secondo Respiro",
    "Seedrot": "Marciume di Semi",
    "Seedstorm": "Tempesta di Semi",
    "Seeing Red": "Vedere Rosso",
    "Seismic Echo": "Eco Sismica",
    "Septic Aftercut": "Taglio Settico",
    "Shadow Duelist": "Duellante d'Ombra",
    "Shadow Quake": "Sisma d'Ombra",
    "Shadowed Steel": "Acciaio Ombrato",
    "Shatterstun": "Stordimento Frantumante",
    "Silent Recovery": "Recupero Silenzioso",
    "Slash And Bash": "Taglia e Percuoti",
    "Slash and Bash": "Taglia e Percuoti",
    "Sonic Daggers": "Pugnali Sonici",
    "Stillwater": "Acqua Ferma",
    "Stonehide": "Pelle di Pietra",
    "Stunning Tempo": "Tempo Stordente",
    "Sudden Stride": "Falcata Improvvisa",
    "Surge Of Mastery": "Ondata di Maestria",
    "Surge of Mastery": "Ondata di Maestria",
    "Surgecasting": "Lancio d'Ondata",
    "Tempo Conversion": "Conversione di Tempo",
    "Temporal Rot": "Marciume Temporale",
    "Thick Skin": "Pelle Spessa",
    "Tidepool": "Pozza di Marea",
    "Timeless Flames": "Fiamme Atemporali",
    "Toxicbloom": "Fiore Tossico",
    "Virulent Casting": "Lancio Virulento",
    "Vital Conduit": "Condotto Vitale",
    "Weak Point Sense": "Senso del Punto Debole",
    "Weaving Jabs": "Jab Intrecciati",
    "Whirl Of Gore": "Vortice di Sangue",
    "Wild Strider": "Passo Silvestre",
    "Wildfire": "Incendio Selvaggio",
    "Winter Focus": "Concentrazione Invernale",
    "Winterguard": "Guardia Invernale",
    "Xwin Dreadhorn": "Cornispavento di Xwin",
}
