# -*- coding: utf-8 -*-
"""Nomi base degli oggetti, piu' i nomi degli incantesimi.

Da qui il risolutore composizionale ricava anche le forme derivate: i gradi
"+1".."+5", il prefisso "Recipe" e il prefisso "Spellbook". Tradurre 90 basi
copre 371 righe.

Una distinzione tenuta di proposito: l'inglese usa sia 'Lesser' sia 'Minor' per
gradi diversi dello stesso consumabile. Reso "Minore" e "Scarsa", altrimenti in
italiano diventerebbero indistinguibili.
"""

ITEMS = {
    # ---- materiali e risorse -----------------------------------------------
    "Alpha Claw": "Artiglio Alfa",
    "Alpha Fur": "Pelliccia Alfa",
    "Apple Seed": "Seme di Melo",
    "Beast Meat": "Carne di Bestia",
    "Critter Meat": "Carne di Bestiola",
    "Chicken Egg": "Uovo di Gallina",
    "Copper Ore": "Minerale di Rame",
    "Droop Core": "Nucleo di Droop",
    "Droop Gelo": "Gelatina di Droop",
    "Dryad Eye": "Occhio di Driade",
    "Dryad Lock": "Ciocca di Driade",
    "Emberbloom Seed": "Seme di Emberbloom",
    "Flax Rope": "Corda di Lino",
    "Flax Seed": "Seme di Lino",
    "Forest King Fur": "Pelliccia del Re della Foresta",
    "Forest King Tine": "Punta di Corno del Re della Foresta",
    "Frayed Cloth": "Stoffa Logora",
    "Glass Vial": "Fiala di Vetro",
    "Goblin King Head": "Testa del Re Goblin",
    "Goblin Tooth": "Dente di Goblin",
    "Large Goblin Tooth": "Dente di Goblin Grande",
    "Hoard King Tooth": "Dente del Re del Tesoro",
    "Heart Oak Planks": "Tavole di Quercia del Cuore",
    "Pinewood Planks": "Tavole di Pino",
    "Linen": "Lino",
    "Oil": "Olio",
    "Rough Paper": "Carta Grezza",
    "Singing Bellflower Seed": "Seme di Campanula Canterina",
    "Stone Nails": "Chiodi di Pietra",
    "Tenderberry Seed": "Seme di Tenderberry",
    "Thaumablossom Seed": "Seme di Thaumablossom",
    "Corrupted Treant Bark": "Corteccia di Treant Corrotto",
    "Corrupted Treant Head": "Testa di Treant Corrotto",
    "Corrupted Treant Heart": "Cuore di Treant Corrotto",
    "Treant Head": "Testa di Treant",
    "Treant Heart": "Cuore di Treant",
    "Treant Wood": "Legno di Treant",
    "Water": "Acqua",
    "Wolf Fang": "Zanna di Lupo",

    # ---- attrezzi e armi ---------------------------------------------------
    "Copper Pickaxe": "Piccone di Rame",
    "Stone Pickaxe": "Piccone di Pietra",
    "Copper Woodcutting Axe": "Ascia da Legna di Rame",
    "Stone Woodcutting Axe": "Ascia da Legna di Pietra",
    "Copper Throwing Knife": "Coltello da Lancio di Rame",
    "Stone Throwing Knife": "Coltello da Lancio di Pietra",
    "Flax Gloves": "Guanti di Lino",
    "Linen Gloves": "Guanti di Tela",

    # ---- cibo e bevande ----------------------------------------------------
    "Apple Juice": "Succo di Mela",
    "Bellflower Soup": "Zuppa di Campanula",
    "Burrow Broth": "Brodo di Tana",
    "Cooked Critter": "Bestiola Cotta",
    "Earlwood Feast": "Banchetto di Earlwood",
    "Emberbless Soup": "Zuppa Benedetta dalla Brace",
    "Fried Chicken Egg": "Uovo Fritto",
    "Hunter's Stew": "Stufato del Cacciatore",
    "Nature's Calm Tonic": "Tonico della Calma Naturale",
    "Nature's Ward Steak": "Bistecca della Protezione Naturale",
    "Poet's Brew": "Infuso del Poeta",
    "Roasted Droop Core": "Nucleo di Droop Arrostito",
    "Tenderberry Tea": "Tè di Tenderberry",
    "Thaumablossom Tea": "Tè di Thaumablossom",
    "Thickblood Broth": "Brodo di Sangue Denso",
    "Warming Broth": "Brodo Riscaldante",
    "Water Flask": "Fiasca d'Acqua",

    # ---- pozioni e consumabili --------------------------------------------
    "Blood Rage Potion": "Pozione della Furia Sanguinaria",
    "Minor Blood Rage Potion": "Pozione Scarsa della Furia Sanguinaria",
    "Elixir of Rebirth": "Elisir della Rinascita",
    "Explosive Flask": "Fiasca Esplosiva",
    "Flaming Oil": "Olio Fiammeggiante",
    "Frosted Oil": "Olio Gelido",
    "Toxic Oil": "Olio Tossico",
    "Oil Flask": "Fiasca d'Olio",
    "Poison Flask": "Fiasca di Veleno",
    "Frostbound Potion": "Pozione del Vincolo Gelido",
    "Inoculation Potion": "Pozione di Inoculazione",
    "Kindling Potion": "Pozione d'Innesco",
    "Lesser Concentration Potion": "Pozione Minore di Concentrazione",
    "Lesser Health Potion": "Pozione Minore di Salute",
    "Lesser Stamina Potion": "Pozione Minore di Vigore",
    "Lesser Concentration Throwflask": "Fiasca da Lancio Minore di Concentrazione",
    "Lesser Health Throwflask": "Fiasca da Lancio Minore di Salute",
    "Lesser Stamina Throwflask": "Fiasca da Lancio Minore di Vigore",
    "Minor Concentration Throwflask": "Fiasca da Lancio Scarsa di Concentrazione",
    "Minor Health Throwflask": "Fiasca da Lancio Scarsa di Salute",
    "Light Bandages": "Bende Leggere",
    "Weak Health Extract": "Estratto Debole di Salute",
    "Weak Magic Extract": "Estratto Debole di Magia",

    # ---- costruzioni presenti solo come ricetta ---------------------------
    "Earlwood Barrel Chair": "Sedia a Botte di Earlwood",
    "Earlwood Brazier": "Braciere di Earlwood",
    "Earlwood Hearth": "Focolare di Earlwood",
    "Earlwood Training Dummy": "Manichino da Allenamento di Earlwood",
    "Heart Oak Doorway": "Vano di Porta di Quercia del Cuore",
    "Heart Oak Mill": "Mulino di Quercia del Cuore",
    "Heartwood Foundation": "Fondazione in Durame",
    "Pinewood Foundation": "Fondazione di Pino",
    "Pinewood Wall": "Muro di Pino",
    "Standing Torch": "Torcia a Stelo",
    "Stone Doorway": "Vano di Porta di Pietra",
    "Treant Wood Stool": "Sgabello di Legno di Treant",

    # ---- nomi degli incantesimi (usati anche da Spells) -------------------
    "Adrenaline": "Adrenalina",
    "Aetherfang Phalanx": "Falange Zanna d'Etere",
    "Alpha Howl": "Ululato Alfa",
    "Barrier": "Barriera",
    "Bash": "Percossa",
    "Black Hole": "Buco Nero",
    "Bramble Fan": "Ventaglio di Spine",
    "Circle of Magic": "Cerchio di Magia",
    "Clear Water": "Acqua Limpida",
    "Combat Medic": "Medico da Campo",
    "Conflagration": "Conflagrazione",
    "Crippling Strike": "Colpo Storpiante",
    "Devour": "Divorare",
    "Empower Ally": "Potenzia Alleato",
    "Entangling Roots": "Radici Avviluppanti",
    "Erupt": "Eruzione",
    "Fireburst": "Scoppio di Fuoco",
    "Flaming Strike": "Colpo Fiammeggiante",
    "Frenzied Slashes": "Tagli Frenetici",
    "Frozen Strike": "Colpo Congelato",
    "Goblin Toss": "Lancio di Goblin",
    "Gust": "Raffica",
    "Heavy Strike": "Colpo Pesante",
    "Infectious Swarm": "Sciame Infettivo",
    "Junk Hail": "Grandine di Rottami",
    "Meteorite": "Meteorite",
    "Rejection": "Repulsione",
    "Ripple": "Ondulazione",
    "Sap Artillery": "Artiglieria di Linfa",
    "Savage Claw": "Artiglio Selvaggio",
    "Seed Bomb": "Bomba di Semi",
    "Shockwave": "Onda di Shock",
    "Spawn Forest Heart": "Evoca Cuore della Foresta",
    "Spirit Swap": "Scambio Spirituale",
    "Tendon Slice": "Taglio dei Tendini",
    "Toxic Slice": "Taglio Tossico",
    "War Banner": "Stendardo di Guerra",
    "Water Surge": "Ondata d'Acqua",
}
