# -*- coding: utf-8 -*-
"""Nomi di incantesimi e abilita' dei mostri.

Molti sono composti da elementi gia' fissati altrove (Droop, Treant, Re della
Foresta, Alfa, Corrotto): qui contano soprattutto la coerenza con quelle scelte
e la distinzione fra abilita' omonime di creature diverse.

Alcune voci sono identificatori interni che il gioco puo' mostrare in debug
('Casting', 'Monster Recovery', 'Stacking Effect'): tradotti comunque, non fanno
danno e restano riconoscibili.
"""

SPELLS = {
    # ---- abilita' del giocatore --------------------------------------------
    "Auto Attack": "Attacco automatico",
    "Attack Swap": "Cambio d'attacco",
    "Casting": "Lancio",
    "Sprinting": "Scatto",
    "Dash": "Scatto rapido",
    "Parry": "Parata",
    "Haste": "Celerità",
    "Retaliation": "Rappresaglia",
    "Rewind": "Riavvolgimento",
    "Enlarge": "Ingrandimento",
    "Reposition": "Riposizionamento",
    "Stacking Effect": "Effetto ad accumulo",
    "Swift Strike": "Colpo Veloce",
    "Relentless Assault": "Assalto Implacabile",
    "Laughing Slashes": "Tagli Beffardi",
    "Shank And Run": "Accoltella e Fuggi",
    "Clone Dagger Throw": "Lancio di Pugnale del Clone",
    "Jolt Dagger": "Pugnale Folgorante",
    "Sonic Bolt": "Dardo Sonico",
    "Spiteful Bolt": "Dardo Malevolo",
    "Temporal Ripple": "Ondulazione Temporale",
    "Shadow Shockwave": "Onda d'Ombra",
    "Stun Shatter Burst": "Scarica Frantumante",
    "Echoes Of Mutilation": "Echi di Mutilazione",
    "Hail Of Arrows": "Pioggia di Frecce",
    "Hunter's Trap": "Trappola del Cacciatore",
    "Seed Bombs": "Bombe di Semi",
    "Blighted Trail": "Scia Infetta",
    "Decay Burst": "Scarica di Decadimento",
    "Poison Erupt": "Eruzione Velenosa",
    "Poison Pool": "Pozza di Veleno",
    "Poison Spores": "Spore Velenose",
    "Venom Spit": "Sputo Velenoso",
    "Oil Pool": "Pozza d'Olio",
    "Oil And Fire": "Olio e Fuoco",
    "Water Pool": "Pozza d'Acqua",
    "Burning Pit": "Fossa Ardente",
    "Bottle Of Fire": "Bottiglia di Fuoco",
    "Bottle Of Fire On Death": "Bottiglia di Fuoco alla Morte",
    "Everburn Mortar": "Mortaio Eternofuoco",
    "Mortar Volley": "Salva di Mortaio",
    "Lightning Surge": "Ondata Fulminea",
    "Storm Aura Shock": "Scossa dell'Aura di Tempesta",
    "Tidal Wave": "Onda di Marea",
    "Invincible Shield": "Scudo Invincibile",
    "Silver Ward": "Guardia d'Argento",
    "Natures Shroud": "Manto della Natura",
    "Floral Flourish": "Fioritura Floreale",
    "Tree Growth": "Crescita dell'Albero",
    "Root Spikes": "Punte di Radice",
    "Root Stomp": "Pestone di Radici",
    "Root Strike Spike": "Spina del Colpo di Radice",
    "Root Surge": "Ondata di Radici",
    "Root Thrust": "Stoccata di Radice",
    "Thorn Spikes": "Punte di Spine",
    "Rotting Roots": "Radici Putrescenti",
    "Rotting Stomp": "Pestone Putrescente",
    "Sap Bloom": "Fioritura di Linfa",
    "Resin Geyser": "Geyser di Resina",
    "Heartbound Tether": "Legame del Cuore",
    "Power Of The Wild": "Potere della Natura Selvaggia",
    "Spawn Elemental Pool": "Evoca Pozza Elementale",
    "Stone Throw": "Lancio di Pietra",
    "Blackhole": "Buco Nero",
    "Command Attack": "Ordine: Attacca",
    "Command Defend": "Ordine: Difendi",
    "Devour Call": "Richiamo Divoratore",
    "Empower Wolf": "Potenzia Lupo",
    "Wolf Pack Sense": "Senso del Branco",
    "Wolf Pounce": "Balzo del Lupo",
    "Rousing Snarl": "Ringhio Incitante",
    "War Roar": "Ruggito di Guerra",
    "Savage Frostbite": "Morso Gelido Selvaggio",
    "Stunning Pounce": "Balzo Stordente",
    "Astral Purr": "Fusa Astrali",
    "Aether Howl": "Ululato d'Etere",
    "Chillwing Descent": "Discesa dell'Ala Gelida",
    "Lunar Tailstorm": "Tempesta di Coda Lunare",
    "Carrion Sweep": "Spazzata Carogna",

    # ---- abilita' delle creature -------------------------------------------
    "Bite": "Morso",
    "Claw": "Artiglio",
    "Corrupted Claw": "Artiglio Corrotto",
    "Alpha Bite": "Morso Alfa",
    "Alpha Pounce": "Balzo Alfa",
    "Alpha Reposition": "Riposizionamento Alfa",
    "Droop Lunge": "Affondo di Droop",
    "Droop Spit": "Sputo di Droop",
    "Droop King Erupt": "Eruzione del Re Droop",
    "Droop King Lunge": "Affondo del Re Droop",
    "Droop King Spit": "Sputo del Re Droop",
    "Corrupted Droop King Erupt": "Eruzione del Re Droop Corrotto",
    "Corrupted Droop King Lunge": "Affondo del Re Droop Corrotto",
    "Corrupted Droop King Spit": "Sputo del Re Droop Corrotto",
    "Treant Attack": "Attacco di Treant",
    "Treant Swipe": "Fendente di Treant",
    "Corrupted Treant Swipe": "Fendente di Treant Corrotto",
    "Corrupted Root Stomp": "Pestone di Radici Corrotte",
    "Corrupted Forest King Phase Change": "Cambio di Fase del Re della Foresta Corrotto",
    "Forest Heart Manager": "Gestore del Cuore della Foresta",
    "Forest Heart Bramble Fan": "Ventaglio di Spine del Cuore della Foresta",
    "Forest Heart Heartbound Tether": "Legame del Cuore della Foresta",
    "Forest Heart Resin Geyser": "Geyser di Resina del Cuore della Foresta",
    "Forest Heart Sap Bloom": "Fioritura di Linfa del Cuore della Foresta",
    "Woldroot Stomp": "Pestone di Woldroot",
    "Woldroot Swipe": "Fendente di Woldroot",
    "Briarheart Stomp": "Pestone di Briarheart",
    "Crownbreaker Sweep": "Spazzata Spaccacorona",
    "Seismic Throne Slam": "Schianto del Trono Sismico",
    "Gobo Charge": "Carica Gobo",
    "Goblin Charge": "Carica Goblin",
    "Gotburg Fire": "Fuoco di Gotburg",
    "Club Swing And Slam": "Mazzata e Schianto",
    "Club Swing And Slam Stuck": "Mazzata e Schianto Bloccati",
    "Smashmouth Club Swing And Slam": "Mazzata e Schianto di Smashmouth",
    "Minotaur Attack": "Attacco del Minotauro",
    "Flamebound Charge": "Carica Infuocata",
    "Flamecaller Pit": "Fossa dell'Evocafiamme",
    "Dragon's Breath": "Soffio del Drago",
    "Elf Melee Attack": "Attacco in Mischia dell'Elfo",
    "Elf Final Attack": "Attacco Finale dell'Elfo",
    "Human Melee Attack": "Attacco in Mischia dell'Umano",
    "Fairy Invulnerable": "Fata Invulnerabile",
    "Monster Dash Basic": "Scatto Base del Mostro",
    "Monster Recovery": "Recupero del Mostro",
    "Monster Recovery Extended": "Recupero Esteso del Mostro",
    "Monster Recovery Long": "Recupero Lungo del Mostro",
    "Monster Recovery Medium": "Recupero Medio del Mostro",

    # ---- abilita' dei personaggi nominati ----------------------------------
    "Althaeas Flourish": "Fioritura di Althaea",
    "Althaeas Spikes": "Punte di Althaea",
    "Althaeas Swap": "Scambio di Althaea",
    "Althaeas Tidal Wave": "Onda di Marea di Althaea",
    "Ceres Ether Missile": "Dardo d'Etere di Ceres",
}
