# -*- coding: utf-8 -*-
"""Proposte italiane per il glossario dei termini ricorrenti di Dimraeth.

Ogni voce: termine inglese -> (italiano, stato, nota)

stati:
  OK       proposta solida, allineata a come DE/ES/PT hanno reso il termine
  KEEP     nome proprio: resta in inglese (e' cosi' anche nelle altre lingue)
  REVIEW   serve vederlo in gioco: senso ambiguo fuori contesto
  DROP     falso positivo del riconoscimento automatico, non e' un termine di gioco

Le voci OK e KEEP sono applicabili come sono. REVIEW e DROP vanno guardate a mano.
"""

PROPOSALS = {
    # ---- risorse e statistiche di base ------------------------------------
    "Health":                     ("Salute", "OK", ""),
    "Full Health":                ("Salute massima", "OK", ""),
    "Stamina":                    ("Vigore", "OK", "ES usa 'Aguante'; 'Stamina' invariato e' l'alternativa"),
    "Stamina Regeneration":       ("Rigenerazione del vigore", "OK", ""),
    "Concentration":              ("Concentrazione", "OK", "ES devia in 'Enfoque' (Focus)"),
    "Concentration Regeneration": ("Rigenerazione della concentrazione", "OK", ""),
    "Regeneration":               ("Rigenerazione", "OK", ""),
    "Armor":                      ("Armatura", "OK", ""),
    "Resistance":                 ("Resistenza", "OK", ""),
    "Fire Resistance":            ("Resistenza al fuoco", "OK", ""),
    "Attack Speed":               ("Velocità d'attacco", "OK", ""),
    "Movement Speed":             ("Velocità di movimento", "OK", ""),
    "Spell Haste":                ("Celerità magica", "OK", ""),
    "Critical Chance":            ("Probabilità di critico", "OK", ""),
    "Crit Chance":                ("Probabilità di critico", "OK", "forma abbreviata dello stesso stat"),
    "Critical Damage":            ("Danno critico", "OK", ""),
    "Crit Damage":                ("Danno critico", "OK", "forma abbreviata dello stesso stat"),
    "Physical Power":             ("Potere fisico", "OK", ""),
    "Magic Power":                ("Potere magico", "OK", ""),
    "Physical Piercing":          ("Penetrazione fisica", "OK",
                                   "Piercing reso con Penetrazione: con Perforazione, Thrust Piercing darebbe 'Perforazione perforante'"),
    "Damage":                     ("Danno", "OK", ""),
    "Increase":                   ("Aumento", "OK", ""),
    "Bonus":                      ("Bonus", "OK", ""),
    "Duration":                   ("Durata", "OK", ""),
    "Charges":                    ("Cariche", "OK", ""),
    "Charge":                     ("Carica", "OK", ""),
    "Rounds":                     ("Round", "OK", "invariato nel contesto di combattimento"),
    "Betting Rounds":             ("Giri di puntata", "OK",
                                   "termine a se': piu' lungo, quindi consuma Rounds"),
    "Attacks":                    ("Attacchi", "OK", ""),

    # ---- tipi di danno -----------------------------------------------------
    "Physical":                   ("Fisico", "OK", ""),
    "Physical Damage":            ("Danno fisico", "OK", ""),
    "Magic Damage":               ("Danno magico", "OK", ""),
    "Rate Of Fire":               ("cadenza di tiro", "OK",
                                   "termine a se': qui Fire e' il tiro, non l'elemento"),
    "Earth Shattering":           ("spaccaterra", "OK",
                                   "idioma inglese, non il prefisso di ramo Shattering"),
    "Fire":                       ("Fuoco|scaglia|scocca|lancia", "OK",
                                   "anche verbo 'to fire': scaglia un fulmine"),
    "Fire Damage":                ("Danno da fuoco", "OK", ""),
    "Ice Damage":                 ("Danno da ghiaccio", "OK", ""),
    "Ether":                      ("Etere", "OK", ""),
    "Ether Damage":               ("Danno da etere", "OK", ""),
    "Decay":                      ("Decadimento|calo", "OK",
                                   "tipo di danno Decadimento; calo di un indicatore"),
    "Decay Damage":               ("Danno da decadimento", "OK", ""),
    "Electricity":                ("Elettricità|elettrico", "OK",
                                   "anche aggettivo: colpi elettrici"),
    "Electricity Damage":         ("Danno da elettricità", "OK", ""),
    "Blunt":                      ("Contundente", "OK", ""),
    "Blunt Damage":               ("Danno contundente", "OK", ""),
    "Thrust":                     ("Perforante|stoccata", "OK",
                                   "tipo di danno Perforante; nome d'attacco Stoccata"),
    "Thrust Damage":              ("Danno perforante", "OK", ""),
    "Strike":                     ("Taglio|colpo", "OK",
                                   "tipo di danno Taglio; nei nomi di attacco Colpo"),
    "Strike Damage":              ("Danno da taglio", "OK", ""),
    "Stun Damage":                ("Danno da stordimento", "OK", ""),
    "Stun Build":                 ("Accumulo di stordimento", "OK", ""),

    # ---- stati alterati ----------------------------------------------------
    "Bleeding":                   ("Sanguinamento|sanguinante", "OK",
                                   "aggettivo per i bersagli: sanguinanti"),
    "Poison":                     ("Veleno", "OK", ""),
    "Poisoned":                   ("Avvelenato|veleno", "OK",
                                   "anche perifrasi: nemico con accumuli di Veleno"),
    "Poison Mist":                ("Nebbia velenosa", "OK", ""),
    "Poison Cure":                ("Antidoto", "OK",
                                   "resa idiomatica, non 'Cura del veleno'"),
    "Burning":                    ("Ustione|ustionato|ardente|bruci", "OK",
                                   "stato Ustione; nel parlato e' il verbo: 'bruci le energie'"),
    "Chill":                      ("Gelo", "OK", ""),
    "Chilled":                    ("Assiderato", "OK", "'Congelato' se esiste uno stato Frozen distinto"),
    "Frostbound":                 ("Vincolo gelido", "OK", ""),
    "Stunned":                    ("Stordito", "OK", ""),
    "Slow":                       ("Rallentamento|rallenta|lento", "OK",
                                   "stato Rallentamento, verbo rallenta, aggettivo 'passi lenti'"),
    "Rage":                       ("Furia|rabbia|ira", "OK",
                                   "meccanica: Furia; nei dialoghi e' il sostantivo comune"),
    "Frenzy":                     ("Frenesia", "OK", ""),
    "Inoculation":                ("Inoculazione", "OK", ""),
    "Contagion":                  ("Contagio", "OK", ""),
    "Outbreak":                   ("Epidemia", "OK", ""),
    "Ruptured":                   ("Lacerato", "OK", ""),
    "Kindled":                    ("Ravvivato", "OK", ""),
    "Kindling":                   ("Innesco", "OK", ""),
    "Corruption":                 ("Corruzione", "OK", ""),
    "Shock":                      ("Scossa", "OK", ""),
    "Pressure":                   ("Pressione", "OK", ""),
    "Interrupting":               ("Interruzione|interrompendo", "OK",
                                   "anche gerundio nelle descrizioni"),
    "Stealth":                    ("Furtività", "OK", ""),

    # ---- abilità e incantesimi ---------------------------------------------
    "Fireball":                   ("Palla di fuoco", "OK", ""),
    "Inferno":                    ("Inferno", "REVIEW", "MIXED fra le lingue ufficiali"),
    "Blizzard":                   ("Tormenta", "OK",
                                   "scelto Tormenta (tempesta di neve) su Bufera, generica"),
    "Vortex":                     ("Vortice", "OK", ""),
    "Pulverize":                  ("Polverizza", "OK", ""),
    "Cleave":                     ("Fendente", "OK", ""),
    "Vehement Cleave":            ("Fendente veemente", "OK", ""),
    "Quake":                      ("Sisma", "OK", ""),
    "Tyrant Quake":               ("Sisma del Tiranno", "OK", ""),
    "Seismic Stampede":           ("Carica sismica", "OK", ""),
    "Stampede":                   ("Carica travolgente", "OK", ""),
    "Boulder Toss":               ("Lancio di masso", "OK", ""),
    "Onslaught":                  ("Assalto", "OK", ""),
    "Limitless Onslaught":        ("Assalto illimitato", "OK", ""),
    "Mutilation":                 ("Mutilazione", "OK", ""),
    "Echoes of Mutilation":       ("Echi di mutilazione", "OK", ""),
    "Surge":                      ("Ondata", "OK", ""),
    "Temporal Surge":             ("Ondata temporale", "OK", ""),
    "Temporal Echo":              ("Eco temporale", "OK", ""),
    "Echo":                       ("Eco", "OK", ""),
    "Echoed":                     ("Riecheggiato|Eco temporale", "OK",
                                   "perifrasi: nemici affetti da Eco temporale"),
    "Echo Rift":                  ("Fenditura d'eco", "OK", ""),
    "Rift":                       ("Fenditura", "OK", ""),
    "Chrono Spike":               ("Spina cronale", "OK", ""),
    "Void":                       ("Vuoto", "OK", ""),
    "Timeless Void":              ("Vuoto eterno", "OK", ""),
    "Convergence":                ("Convergenza", "OK", ""),
    "Shadow Convergence":         ("Convergenza d'ombra", "OK", ""),
    "Shadow Clone":               ("Clone d'ombra", "OK", ""),
    "Shadow Clones":              ("Cloni d'ombra", "OK", ""),
    "Clone":                      ("Clone", "OK", ""),
    "Shadow Dagger":              ("Pugnale d'ombra", "OK", ""),
    "Shadow Daggers":             ("Pugnali d'ombra", "OK", ""),
    "Shadow Art":                 ("Arte dell'ombra", "OK", ""),
    "Vanish":                     ("Dissolvenza|svanisci|furtività", "OK",
                                   "anche verbo imperativo"),
    "Vanishing Strike":           ("Colpo dissolvente", "OK", ""),
    "Double Strike":              ("Colpo doppio", "OK", ""),
    "Wave Strike":                ("Colpo d'onda", "OK", ""),
    "Wave":                       ("Onda", "OK", ""),
    "Furious Strike":             ("Colpo furioso", "OK", ""),
    "Backstep":                   ("Passo indietro", "OK", ""),
    "Backstep Strike":            ("Colpo in arretramento", "OK", ""),
    "Quick Jab":                  ("Jab rapido", "OK", "terminologia pugilistica, come in ES"),
    "Straight":                   ("Diretto|Scala|dritt", "OK",
                                   "pugilato Diretto, poker Scala; nel parlato 'dritto al punto'"),
    "Straight to the":            ("Subito al|dritto al|dritta al", "OK",
                                   "locuzione: 'straight to the point/ledger', non il Diretto"),
    "Strong Straight":            ("Diretto potente", "OK", ""),
    "Hook":                       ("Gancio", "OK", ""),
    "Power Hook":                 ("Gancio potente", "OK", ""),
    "Dance":                      ("Danza", "OK", ""),
    "Blade Dance":                ("Danza delle lame", "OK", ""),
    "Glide":                      ("Scivolata", "OK", ""),
    "Frost Glide":                ("Scivolata gelida", "OK", ""),
    "Javelin":                    ("Giavellotto", "OK", ""),
    "Frost Javelin":              ("Giavellotto gelido", "OK", ""),
    "Aimed Shot":                 ("Tiro mirato", "OK", ""),
    "Shot":                       ("Tiro", "OK", ""),
    "Arrows":                     ("Frecce", "OK", ""),
    "Daggers":                    ("Pugnali", "OK", ""),
    "Breath":                     ("Soffio", "OK", ""),
    "Hail":                       ("Grandine|pioggia", "OK",
                                   "Hail Of Arrows e' pioggia di frecce in italiano"),
    "Shards":                     ("Frammenti", "OK", ""),
    "Plague Shards":              ("Frammenti di peste", "OK", ""),
    "Plague Magic":               ("Magia della peste", "OK", ""),
    "Ice Pool":                   ("Pozza di ghiaccio", "OK", ""),
    "Ice Pools":                  ("Pozze di ghiaccio", "OK", ""),
    "Channel":                    ("Canalizzazione", "OK", ""),
    "Final Attack":               ("Attacco finale", "OK", ""),
    "Ranged Final Attack":        ("Attacco finale a distanza", "OK", ""),
    "Trap":                       ("Trappola", "OK", ""),
    "Cornu Charge":               ("Carica di Cornu", "OK", "'Cornu' e' nome proprio, resta"),
    "Stone":                      ("Pietra", "OK", ""),
    "Weapon Swap":                ("Cambio arma", "OK", ""),
    "Sword Swap":                 ("Cambio a spada", "OK", ""),
    "Crossbow Swap":              ("Cambio a balestra", "OK", ""),
    "Swap":                       ("Cambio|passa", "OK",
                                   "anche verbo: 'Passa alla mappa'"),

    # ---- creature e personaggi ---------------------------------------------
    "Goblin":                     ("Goblin", "OK", "invariato, come in ES"),
    "Goblins":                    ("Goblin", "OK", "invariato anche al plurale"),
    "Goblin King":                ("Re Goblin", "OK", ""),
    "Dragon":                     ("Drago", "OK", ""),
    "Dryad":                      ("Driade", "OK", ""),
    "Dryads":                     ("Driadi", "OK", ""),
    "Wolves":                     ("Lupi", "OK", ""),
    "Minotaur":                   ("Minotauro", "OK", ""),
    "Monster":                    ("Mostro", "OK", ""),
    "Treant":                     ("Treant", "OK",
                                   "invariato, come Goblin; 'Ent' era l'alternativa, scartata"),
    "Treants":                    ("Treant", "OK", "plurale invariato: 'i Treant'"),
    "Corrupted Treant":           ("Treant corrotto", "REVIEW", "dipende dalla scelta su 'Treant'"),
    "Dwarf":                      ("Nano|Nana", "OK", "razza giocabile, gia' in Attributes"),
    "Dwarves":                    ("Nani|Nane", "OK", ""),
    "dwarf":                      ("nano|nana|nanic", "OK",
                                   "Saqi e' una nana: serve anche il femminile e l'aggettivo 'nanico'"),
    "dwarves":                    ("nani|nane|nanic", "OK", ""),
    "Dwarven":                    ("Nanico|nanica|nani", "OK",
                                   "anche per perifrasi: 'i cancelli dei nani'"),
    "Elven":                      ("Elfico|elfa|elfo|elfi", "OK",
                                   "aggettivo; come sostantivo concorda in genere e numero"),
    "Hunter":                     ("Cacciatore", "OK", ""),
    "Traveller":                  ("Viandante", "OK", ""),
    "Mayor":                      ("Sindaco", "OK", ""),
    "King":                       ("Re", "OK", ""),
    "Forest King":                ("Re della Foresta", "OK", ""),
    "Old Ones":                   ("Antichi", "OK", ""),
    "Players":                    ("Giocatori", "OK", ""),

    # ---- luoghi, strutture, interfaccia ------------------------------------
    "Forest":                     ("Foresta", "OK", ""),
    "Forest Heart":               ("Cuore della Foresta", "OK", ""),
    "Heart Oak":                  ("Quercia del Cuore", "OK", ""),
    "Sanctum":                    ("Santuario", "OK", ""),
    "Waygate":                    ("Varco", "OK", "'Portale' e' l'alternativa; decidere una volta"),
    "Waygates":                   ("Varchi|varco", "OK",
                                   "dopo 'qualsiasi' l'italiano vuole il singolare"),
    "Guild":                      ("Gilda", "OK", ""),
    "Guild Hall":                 ("Sede della Gilda", "OK", ""),
    "Deed Board":                 ("Bacheca degli incarichi", "OK", ""),
    "Shop":                       ("Negozio", "OK", ""),
    "Mill":                       ("Mulino", "OK", ""),
    "Inventory":                  ("Inventario", "OK", ""),
    "Hide Item Tooltips":         ("Nascondi descrizioni oggetti", "OK", "voce di opzioni"),
    "Hunger":                     ("Fame", "OK", ""),
    "Thirst":                     ("Sete", "OK", ""),
    "Nourishment":                ("Nutrimento", "OK", ""),
    "Well Rested Buff":           ("Bonus Ben Riposato", "OK", ""),
    "Acorn":                      ("Ghianda|Acorn", "OK",
                                   "anche nome proprio: l'amico di Basilton resta 'Acorn'"),
    "Prime Principles":           ("Principi Primi", "OK", ""),

    # ---- flora inventata: invariata come nelle altre lingue ----------------
    "Thaumablossom":              ("Thaumablossom", "KEEP", ""),
    "Emberbloom":                 ("Emberbloom", "KEEP", ""),
    "Glimmerflax":                ("Glimmerflax", "KEEP", ""),
    "Wildwood Pine":              ("Pino di Wildwood", "OK", "'Wildwood' resta, come in ES"),
    "Singing Bellflower":         ("Campanula Canterina", "OK", ""),
    # nomi individuali delle piante di Basilton: nomi propri, non specie
    "Tender":                     ("Tender", "KEEP", "nome di una pianta, non l'aggettivo"),
    "Plump":                      ("Plump", "KEEP", ""),
    "Rosary":                     ("Rosary", "KEEP", ""),
    "Dandelion":                  ("Dandelion", "KEEP", ""),
    "Worps":                      ("worp", "OK", "plurale invariato"),
    "worps":                      ("worp", "OK", "plurale invariato"),

    # ---- nomi propri: invariati --------------------------------------------
    "Dimraeth":                   ("Dimraeth", "KEEP", ""),
    "Earlwood":                   ("Earlwood", "KEEP", ""),
    "Earlwood Village":           ("Villaggio di Earlwood", "OK", "toponimo composto: il nome resta"),
    "Wildwood":                   ("Wildwood", "KEEP", ""),
    "Aldoria":                    ("Aldoria", "KEEP", ""),
    "Mirkea":                     ("Mirkea", "KEEP", ""),
    "Heimen":                     ("Heimen", "KEEP", ""),
    "Sylbos":                     ("Sylbos", "KEEP", ""),
    "Dolmarok":                   ("Dolmarok", "KEEP", "dominio di Sylbos"),
    "Mount Grandor":              ("Monte Grandor", "OK", ""),
    "The Hearth at Road’s Edge":  ("Il Focolare sul Ciglio della Strada", "OK",
                                   "la taverna di Saqi; distinta da Earlwood Hearth -> Focolare di Earlwood"),
    "Road’s Edge":                ("Ciglio della Strada", "OK", "forma breve della stessa taverna"),
    "Iron Guardians":             ("Guardiani di Ferro", "OK", "dai racconti di Barakthrum, non i golem"),
    "Empire of Xwin":             ("Impero di Xwin", "OK",
                                   "non ampliare in Impero dei Minotauri dove l'inglese non lo fa"),
    "Basilton's Note":            ("Biglietto di Basilton", "OK",
                                   "un messaggio scritto: 'biglietto', non la 'Nota' dell'interfaccia"),
    "The Adventurer Captain":     ("Il capitano degli avventurieri", "OK", "titolo di Corin"),
    "The Venerable Wizard":       ("Il venerabile mago", "OK", "titolo di Faustas"),
    "One of the Scavengers":      ("Uno degli sciacalli", "OK",
                                   "titolo della guardia: saccheggio dei caduti"),
    "Child oF Earlwood":          ("Bambino di Earlwood", "OK", "refuso 'oF' nell'originale"),
    "The young dwarf":            ("La giovane nana", "OK", "titolo di Saqi, al femminile"),
    "Lumen Realm":                ("regno di Lumen", "OK",
                                   "l'originale alterna Lumen (2) e Numen (3): incoerenza conservata"),
    "Faustas's Rest":             ("Riposo di Faustas", "OK",
                                   "distinto da Faustas's Tower; AREA_FAUSTASREST mostra pero' 'Earlwood'"),
    "Elven Imperial era":         ("era imperiale elfica", "OK", ""),
    "Emissaries":                 ("Emissari", "OK", ""),
    "Emissary":                   ("Emissario", "OK", "maiuscola quando e' funzione divina"),
    "The Travelling Merchant":    ("Il Mercante Itinerante", "OK", "titolo di Befr"),
    "Dwarven Poet":               ("Poeta Nanico", "OK", "titolo di Heimen"),
    "The Earlwood Guild Trainer": ("L'Addestratore della Gilda di Earlwood", "OK", "titolo di Rahaner"),
    "Adventurers’ Guild":        ("Gilda degli Avventurieri", "OK", "apostrofo tipografico"),
    "Scroll of Retraining":       ("Pergamena di Riaddestramento", "OK", "da confermare in gioco"),
    "Skill Return Scroll":        ("Pergamena di Recupero Abilità", "OK", "da confermare in gioco"),
    "Skill Return Book":          ("Libro di Recupero Abilità", "OK", "da confermare in gioco"),
    "Ceres":                      ("Ceres", "KEEP", ""),
    "Barakthrum":                 ("Barakthrum", "KEEP", ""),
    "Xwin":                       ("Xwin", "KEEP", "impero e citta' dei minotauri, non un identificatore"),
    "Fairweather":                ("Fairweather", "KEEP", "cognome di Tamsin"),
    "Duratianus":                 ("Duratianus", "KEEP", ""),
    "Aldoron":                    ("Aldoron", "KEEP", ""),
    "Mor’daneth":                 ("Mor’daneth", "KEEP", "apostrofo tipografico, come nell'originale"),
    "Elaria":                     ("Elaria", "KEEP", ""),
    "Adlan":                      ("Adlan", "KEEP", "dio della giustizia"),
    "Agir":                       ("Agir", "KEEP", ""),
    "Marina":                     ("Marina", "KEEP", "divinita' delle acque, non il sostantivo comune"),
    "Akolasis":                   ("Akolasis", "KEEP", ""),
    "Scriptura Principiorum":     ("Scriptura Principiorum", "KEEP", "titolo latino, resta tale"),
    "The Wildwood Golem":         ("Il Golem di Wildwood", "OK", "titolo di Basilton"),
    "The Earlwood Banner Weaver": ("La Tessitrice di Stendardi di Earlwood", "OK", "titolo di Tamsin"),
    "The Earlwood Guild Leader":  ("Il capo della Gilda di Earlwood", "OK", "titolo di Alaric"),
    "The Earlwood Scout":         ("L'esploratore di Earlwood", "OK", "titolo di Eldorian"),
    "Chosen of the Forest":       ("Prescelto della Foresta", "OK", "titolo di Alaric"),
    "Green Knight":               ("Cavaliere Verde", "OK", "proclama il Prescelto per volonta' di Ceres"),
    "Veylenth Vordae":            ("Veylenth Vordae", "KEEP", "denominazione elfica"),
    "Age of Elven Atrocity":      ("Era dell'Atrocità Elfica", "OK", "glossa storica della Veylenth Vordae"),
    "Wildroot Father":            ("Padre delle Radici Selvatiche", "OK", "epiteto di Aelwynor"),
    "Aelwynor":                   ("Aelwynor", "KEEP", ""),
    "Fangra":                     ("Fangra", "KEEP", ""),
    "Bashers":                    ("Picchiatori", "OK", "da Goblin Basher -> Goblin Picchiatore"),
    "Indulgence":                 ("Indulgenza", "OK", "qualifica dei Goblin, maiuscola nell'originale"),
    "Guild Mentor":               ("Mentore della Gilda", "OK", "ruolo di Rahaner"),
    "Guild Shop":                 ("Negozio della Gilda", "OK", "gestito da Tamsin"),
    "Faustas's Tower":            ("Torre di Faustas", "OK", ""),
    "Eternal Forest":             ("Foresta Eterna", "OK", ""),
    "Forest Meet":                ("Raduno della Foresta", "OK", "assemblea degli spiriti"),
    "Forest’s Edge":             ("Margini della Foresta", "OK",
                                   "coerente con Forests Edge Homestead -> Fattoria ai Margini della Foresta"),
    "Forest's Edge":              ("Margini della Foresta", "OK", "variante con apostrofo dritto"),
    "Great Iniquities":           ("Grandi Iniquità", "OK", "potenze contrapposte ai Principi Primi"),
    "Iniquities":                 ("Iniquità", "OK", ""),
    "Iniquity":                   ("Iniquità", "OK", ""),
    "Old Gods":                   ("Antichi Dei", "OK", "distinti dagli Old Ones -> Antichi"),
    "Old Faith":                  ("Antica Fede", "OK", "minuscolo nel parlato non titolato"),
    "Elven Tablet":               ("Tavoletta Elfica", "OK", ""),
    "Exile Of Xwin":              ("Esule di Xwin", "OK", "titolo di Manga"),
    "Minotaur Empire":            ("Impero dei Minotauri", "OK", ""),
    "Southern Barrens":           ("Terre Aride Meridionali", "OK", ""),
    "Barrens":                    ("Terre Aride", "OK", "regione d'origine di Manga"),
    "Numen":                      ("Numen", "KEEP", "natura del termine da confermare in gioco"),
    "Choking Vine":               ("Vite Soffocante", "OK", ""),
    "The Gentlest Spirit":        ("Lo spirito più gentile", "OK", "titolo di Myrll"),
    "Elven Purge":                ("Purga Elfica", "OK", ""),
    "Tree-Father":                ("Padre degli Alberi", "OK",
                                   "l'originale alterna Tree-Father, Treefather e tree-father"),
    "Treefathers":                ("Padri degli Alberi", "OK", ""),
    "tree-father":                ("padre degli alberi", "OK", ""),
    "Praesidiism":                ("Presidiismo", "OK",
                                   "dottrina di Manga, unico '-ism' del gioco: da praesidium/presidio"),
    "Rivercaller":                ("Rivercaller", "REVIEW", "se e' un titolo e non un nome, va tradotto"),
    "Haylor":                     ("Haylor", "KEEP", ""),
    "Haylors":                    ("Haylor", "KEEP", "plurale invariato"),
    "Alaric":                     ("Alaric", "KEEP", ""),
    "Basilton":                   ("Basilton", "KEEP", ""),
    "Tamsin":                     ("Tamsin", "KEEP", ""),
    "Corin":                      ("Corin", "KEEP", ""),
    "Myrll":                      ("Myrll", "KEEP", ""),
    "Eldorian":                   ("Eldorian", "KEEP", ""),
    "Rahaner":                    ("Rahaner", "KEEP", ""),
    "Saqi":                       ("Saqi", "KEEP", ""),
    "Faustas":                    ("Faustas", "KEEP", ""),
    "Befr":                       ("Befr", "KEEP", ""),
    "Manga":                      ("Manga", "KEEP", ""),

    # ---- prefissi dei rami dell'albero delle abilita' ----------------------
    # Sono aggettivi che seguono il nome dell'abilita' in italiano ("Fendente
    # Lacerante"). Ho scelto forme in -ante/-ente perche' sono INVARIANTI per
    # genere: eliminano ogni problema di accordo nelle cornici generate.
    "Rending":                    ("Lacerante|squarcio", "OK",
                                   "aggettivo nei rami, sostantivo negli affissi runa"),
    "Enraging":                   ("Infuriante", "OK", "invariante per genere"),
    "Raging":                     ("Furente", "OK", "invariante per genere"),
    "Echoing":                    ("Echeggiante", "OK", "invariante per genere"),
    "Chilling":                   ("Agghiacciante", "OK", "invariante per genere"),
    "Corrupting":                 ("Corrompente", "OK", "invariante per genere"),
    "Purging":                    ("Purgante", "OK", "invariante per genere"),
    "Harvesting":                 ("Mietente", "OK", "invariante per genere"),
    "Surging":                    ("Montante", "OK", "invariante per genere"),
    "Coagulating":                ("Coagulante", "OK", "invariante per genere"),
    "Inoculating":                ("Inoculante", "OK", "invariante per genere"),
    "Flashheating":               ("Incandescente", "OK", "invariante per genere"),
    "Envenoming":                 ("Avvelenante", "OK", "invariante per genere"),
    "Flaring":                    ("Fiammeggiante", "OK", "invariante per genere"),
    "Shattering":                 ("Frantumante|frantumazione", "OK",
                                   "aggettivo nei rami, sostantivo nei nomi di set"),
    "Fracturing":                 ("Fratturante|incrinatura", "OK",
                                   "aggettivo nei rami, sostantivo negli affissi runa"),
    "Spike":                      ("Spina", "OK", ""),

    # ---- nomi di meccanica che frammentavano le cornici -------------------
    "Piercing":                   ("Penetrazione|trafittura|penetrante", "OK",
                                   "statistica: Penetrazione; affisso di runa: Trafittura, per non confonderlo con la statistica"),
    "Cooldown":                   ("Tempo di recupero", "OK", ""),
    "On Cooldown":                ("In recupero", "OK",
                                   "termine a se': l'etichetta di stato non dice 'tempo'"),
    "Temporal":                   ("Temporale", "OK", "aggettivo, invariante"),
    "Surged":                     ("Montante", "OK", ""),

    # ---- emersi dalla traduzione di Quests --------------------------------
    # Proposte del traduttore, promosse a vincolo: da qui in avanti legano
    # tutta la prosa restante, cosi' i nomi non divergono fra categorie.
    "Brother Generals":           ("Generali Fratelli", "OK", ""),
    "Corrupted Guardian":         ("Guardiano corrotto", "OK", ""),
    "Corrupted Hunters":          ("Cacciatori corrotti", "OK", ""),
    "Corrupted Wolves":           ("Lupi corrotti", "OK", ""),
    "Forest Golem":               ("Golem della Foresta", "OK", ""),
    "Grove Guardian":             ("Guardiana del Boschetto", "OK", ""),
    "Hopeful Shepherd":           ("Pastore fiducioso", "OK", ""),
    "Cordwyn Yard":               ("Deposito di Cordwyn", "OK", ""),
    "Earlwood Quarry":            ("Cava di Earlwood", "OK", ""),
    "Broken Waygate Clearing":    ("Radura del Varco Infranto", "OK", ""),
    "Giant's Trench":             ("Trincea del Gigante", "OK", ""),
    "Wayfinder Line":             ("Linea dei Cercavia", "OK", ""),
    "Silent Path":                ("Sentiero Silenzioso", "OK", ""),
    "Shining Fungus Grove":       ("Boschetto dei Funghi Luminosi", "OK", ""),
    "Waywell":                    ("Pozzo del Cammino", "OK", ""),
    "Forest Entrance":            ("Ingresso della Foresta", "OK", ""),
    "King's Path":                ("Sentiero del Re", "OK", ""),
    "Trail Fork":                 ("Bivio del Sentiero", "OK", ""),
    "River Crossing":             ("Passaggio sul Fiume", "OK", ""),
    "Old Stump":                  ("Vecchio Ceppo", "OK", ""),
    "Clear Spring":               ("Sorgente Limpida", "OK", ""),
    "Nesting Hollow":             ("Conca dei Nidi", "OK", ""),
    "Waystone Burrow":            ("Tana della Pietra del Cammino", "OK", ""),
    "waystone":                   ("pietra del cammino", "OK", ""),
    "ward-stone":                 ("pietra protettiva", "OK", ""),
    "ward stake":                 ("palo protettivo", "OK", ""),
    "elder-tree sap":             ("linfa dell'albero antico", "OK", ""),
    "caretaker's gem":            ("gemma del custode", "OK", ""),
    "dryad-touched water":        ("acqua toccata dalle driadi", "OK", ""),
    "chime":                      ("sonaglio", "OK", ""),
    "beacon":                     ("segnalatore", "OK",
                                   "coerente con l'interfaccia: Piazza segnalatore"),
    "Forge Anvil":                ("Incudine della Fucina", "OK", ""),
    "runesmithing":               ("forgiatura runica", "OK", ""),
    "rune smith":                 ("fabbro runico", "OK", ""),
    "enchanted spindle":          ("fuso incantato", "OK", "lo strumento, distinto dal telaio"),
    "enchanted soil":             ("terra incantata", "OK", "la terra del corpo di Basilton"),
    "ward-work":                  ("trama protettiva", "OK", "la filatura di Tamsin"),
    "banner of light":            ("stendardo di luce", "OK", ""),
    "pennant":                    ("gagliardetto", "OK", "distinto da banner -> stendardo"),
    "fertiliser":                 ("fertilizzante", "OK", "grafia britannica, l'unica presente"),
    "fish-scarecrows":            ("spaventapasseri a forma di pesce", "OK",
                                   "raffigurano JJ, non servono a scacciare pesci"),
    "passing-ritual":             ("rito di passaggio del dono", "OK",
                                   "il passaggio dei worp fra i domini divini"),
    "memorial wall":              ("muro dei caduti", "OK", "da confermare in gioco"),
    "elder tree":                 ("albero antico", "OK",
                                   "uniformato: 'albero secolare' di dlg1 e' stato allineato"),
    "forest gate":                ("accesso alla foresta", "OK",
                                   "passaggio fisico, distinto da Waygate -> Varco"),
    "tree-folk":                  ("gente degli alberi", "OK", "collettivo, non una specie nuova"),
    "discipline scout":           ("ricognizione disciplinare", "OK",
                                   "scout e' l'attivita', non una persona"),
    "perimeter pass":             ("giro del perimetro", "OK", ""),
    "scout posts":                ("postazioni degli esploratori", "OK", ""),
    "dreamweaver":                ("tessitore di sogni", "OK", "autodefinizione di Heimen, non una classe"),
    "stone-born":                 ("nato nella pietra", "OK", "appellativo, non una razza nuova"),
    "Goblin-Slayer":              ("Ammazza-Goblin", "OK", "soprannome, invariabile per genere"),
    "ration ledgers":             ("registri delle razioni", "OK", "gia' in it/Quests.csv"),
    "beacon kits":                ("kit per i segnalatori", "OK", ""),
    "beacon wards":               ("segnalatori di protezione", "OK", ""),
    "wayfinder duty":             ("servizio dei Cercavia", "OK", "da Wayfinder Line -> Linea dei Cercavia"),
    "wayfinder routes":           ("percorsi dei Cercavia", "OK", ""),
    "By stone and song":          ("Per la pietra e il canto", "OK", "giuramento di Heimen"),
    "new blood":                  ("recluta", "OK", "appellativo di Rahaner; non fissa il sesso"),
    "way-stones":                 ("pietre del cammino", "OK", "variante con trattino di waystone"),
    "bell-lines":                 ("corde con campanelli", "OK", "gia' in it/Quests.csv"),
    "bell-line":                  ("corda con campanelli", "OK",
                                   "distinto da bell-tab -> campanello segnalatore"),
    "rune-smithing":              ("forgiatura runica", "OK", ""),
    "Rune-smithing":              ("Forgiatura runica", "OK", ""),
    "Runesmithing":               ("Forgiatura runica", "OK", ""),
    "rune dust":                  ("polvere runica", "OK", "distinta da Rune Essence"),
    "forge master":               ("maestro fabbro|maestro della fucina", "OK",
                                   "titolo oppure descrizione del ruolo, secondo la frase"),
    "forest-kin":                 ("gente della foresta|della foresta", "OK",
                                   "espressione relazionale: si adatta alla sintassi"),
    "forest kin":                 ("gente della foresta|della foresta", "OK", ""),
    "purge":                      ("purga|epurazione|eliminar", "OK",
                                   "l'evento storico; una volta e' il verbo (purge toxins)"),
    "forward camp":               ("campo avanzato", "OK", ""),
    "Rune Essence":               ("Essenza runica", "OK", ""),
    "Beast Warden":               ("Custode delle Bestie", "OK", ""),
    "Rootweaver":                 ("Tessiradici", "OK", ""),
    "Droop King":                 ("Re Droop", "OK", ""),
    "Hoard King":                 ("Re del Tesoro", "OK", ""),
    # 'ward' da solo non entra: e' dentro Frostward, Burnward, Wardbound e
    # produrrebbe corrispondenze spurie a cavallo dei nomi di set.

    # ---- emersi dal secondo giro (round2) ---------------------------------
    "Builder":                    ("Costruttore", "OK", ""),
    "Critical Rate":              ("Probabilità di critico", "OK", "alias di Critical Chance"),
    "Critical Multiplier":        ("Moltiplicatore critico", "OK", "distinto da Critical Damage"),
    "Healing Power":              ("Potere curativo", "OK", ""),
    "Minion":                     ("servitore", "OK", "creature evocate"),
    "Temporal Cleave":            ("Fendente Temporale", "OK", ""),
    "Third Strike":               ("Terzo Colpo", "OK", ""),
    "Recovery":                   ("Recupero", "OK", ""),
    "Rejuvination":               ("Ringiovanimento", "OK", "grafia anomala nell'originale"),
    "Burning Resistance":         ("Resistenza all'ustione", "OK", "distinta da Fire Resistance"),
    "Burn Resistance":            ("Resistenza all'ustione", "OK", ""),
    "Poison Resistance":          ("Resistenza al veleno", "OK", "distinta da Decay Resistance"),
    "Bleeding Resistance":        ("Resistenza al sanguinamento", "OK", ""),
    "Chill Resistance":           ("Resistenza al gelo", "OK", "distinta da Ice Resistance"),
    "Magic Barrier":              ("Barriera magica", "OK", ""),
    "Fire Aura":                  ("Aura di Fuoco", "OK", ""),
    "Perfect Vanish":             ("Dissolvenza perfetta", "OK", ""),
    "Howl":                       ("Ululato|ulula", "OK", "anche verbo"),
    "Axe Arts":                   ("Arti dell'ascia", "OK", ""),
    "Minotaur Magic":             ("Magia del Minotauro", "OK", ""),
    "spellcrafting":              ("creazione di incantesimi|creare incantesimi", "OK",
                                   "anche in forma verbale: per creare incantesimi"),
    "Stone Foundation":           ("Fondazione di Pietra", "OK", ""),

    # nomi propri e ambientazione
    "Dimraeth Mountains":         ("Monti di Dimraeth", "OK", ""),
    "Imperial Son":               ("Figlio Imperiale", "OK", "titolo di Antark"),
    "Dark Lord":                  ("Signore Oscuro", "OK", "titolo di Sylbos"),
    "Ogre Magi":                  ("Maghi Ogre", "OK", ""),
    "Dark Gods":                  ("Dei Oscuri", "OK", ""),
    "Worp Plant":                 ("Pianta di Worp", "OK", ""),
    "Everlast trees":             ("alberi Everlast", "OK", "specie, nome conservato"),
    "Earlwood Wall":              ("Mura di Earlwood", "OK", ""),
    "Earlwood Wall Banner":       ("Stendardo da Muro di Earlwood", "OK",
                                   "termine a se': e' [Earlwood][Wall Banner], non [Earlwood Wall]"),
    "Goblin Crisis":              ("Crisi dei Goblin", "OK", "evento storico"),
    "Abandoned Farmsteads":       ("Fattorie Abbandonate", "OK", ""),
    "Ford of Garfael":            ("Guado di Garfael", "OK", ""),
    "Corrupted Tree":             ("Albero Corrotto", "OK", ""),
    "Great Academy of Aldoria":   ("Grande Accademia di Aldoria", "OK", ""),
    "Giant Old One's Egg":        ("Uovo dell'Antico Gigante", "OK", ""),
    "ley lines":                  ("linee di forza", "OK", ""),
    "warding banner":             ("stendardo protettivo", "OK", ""),
    "bell-tab":                   ("campanello segnalatore", "OK", ""),

    # ---- emersi dal Codex (round3) ----------------------------------------
    "Decay Channel":              ("Canalizzazione del Decadimento", "OK",
                                   "risolve il dubbio del giro precedente"),
    "Temporal Pressure":          ("Pressione temporale", "OK", ""),
    "Rejuvenation":               ("Ringiovanimento", "OK", "variante di Rejuvination"),
    "Multi-strike":               ("Colpo multiplo", "OK", "variante di Multistrike"),
    "Rupture":                    ("lacerazione", "OK", "esplosione dello stato Lacerato"),
    "Empowered Monsters":         ("Mostri potenziati", "OK", ""),
    "Arcane Shielded":            ("Scudo Arcano", "OK", "potenziamento"),
    "Blighted":                   ("Infetto", "OK", "potenziamento"),
    "Flamecaller":                ("Evocafiamme", "OK", "potenziamento"),
    "Mortar":                     ("Mortaio", "OK", "potenziamento"),
    "Spiteful":                   ("Rancoroso", "OK", "potenziamento"),
    "Storm Aura":                 ("Aura Tempestosa", "OK", "potenziamento"),
    "Unyielding":                 ("Inflessibile", "OK", "potenziamento"),
    "Venomous":                   ("Velenoso", "OK", "potenziamento"),
    "Guard":                      ("Guardia|vigila|custodisci", "OK",
                                   "il corpo di guardia, ma anche il verbo: 'vigila su quel sentimento'"),
    "Lost Boy":                   ("Bambino smarrito", "OK", ""),
    "Suspicious Trader":          ("Mercante sospetto", "OK", ""),
    "Heartwood Door":             ("Porta in Durame", "OK", ""),
    "Heartwood Door Frame":       ("Telaio in Durame", "OK",
                                   "termine a se': e' [Heartwood][Door Frame]"),

    # ---- da guardare in gioco: senso ambiguo fuori contesto ----------------
    "Mother":                     ("", "REVIEW", "epiteto di un personaggio o sostantivo comune?"),
    "Well":                       ("", "REVIEW", "il pozzo come struttura, o l'avverbio 'bene'?"),
    "Hand":                       ("", "REVIEW", "parte del corpo, mano di carte, o titolo?"),
    "Edge":                       ("", "REVIEW", "filo della lama, bordo, o vantaggio?"),
    "Truth":                      ("", "REVIEW", "concetto narrativo o sostantivo comune?"),
    "Deal":                       ("", "REVIEW", "patto narrativo o verbo 'infliggere'?"),
    "Flush":                      ("", "REVIEW", "meccanica a carte o effetto di stato?"),

    # ---- falsi positivi del riconoscimento automatico ----------------------
    "Good":    ("", "DROP", ""),
    "What":    ("", "DROP", ""),
    "Thank":   ("", "DROP", ""),
    "After":   ("", "DROP", ""),
    "Each":    ("", "DROP", ""),
    "Because": ("", "DROP", ""),
    "Many":    ("", "DROP", ""),
    "Still":   ("", "DROP", ""),
    "Where":   ("", "DROP", ""),
    "Since":   ("", "DROP", ""),
    "Right":   ("", "DROP", ""),
    "Here":    ("", "DROP", ""),
    "Perhaps": ("", "DROP", ""),
    "Tell":    ("", "DROP", ""),
    "Grants":  ("", "DROP", ""),
}
