# -*- coding: utf-8 -*-
"""Terzo e ultimo lotto UI: descrizioni di meccaniche, messaggi e testi di schermata.

Da preservare identici: i segnaposto {0} {1} {2}, i tag <color=...> e <i>, e le
sequenze \\n che qui sono due caratteri veri (barra + n), non un ritorno a capo.

Refusi trovati nel CSV inglese di Mudtek, tradotti comunque in italiano:
  - il ringraziamento della demo esiste in due copie, una rimasta in portoghese
  - alcune stringhe sono segnaposto di sviluppo ('Deed Name Deed Name...',
    'Blightseed, Pathweaver, ... Blablabla')
"""

R = {
    # ---- descrizioni di statistiche ---------------------------------------
    "Increases your maximum Health.": "Aumenta la tua salute massima.",
    "Increases your maximum Stamina.": "Aumenta il tuo vigore massimo.",
    "Increases your base Health by a percentage.": "Aumenta la tua salute base di una percentuale.",
    "Increases your base Stamina by a percentage.": "Aumenta il tuo vigore base di una percentuale.",
    "Increases your base Concentration by a percentage.": "Aumenta la tua concentrazione base di una percentuale.",
    "Increases your Armor by a percentage.": "Aumenta la tua armatura di una percentuale.",
    "Increases your Resistance by a percentage.": "Aumenta la tua resistenza di una percentuale.",
    "Increases how much Health you recover over time.": "Aumenta la salute che recuperi nel tempo.",
    "Increases how much Stamina you recover over time.": "Aumenta il vigore che recuperi nel tempo.",
    "Increases maximum Health and Health regeneration.": "Aumenta la salute massima e la sua rigenerazione.",
    "Increases Physical Power and Magic Power.": "Aumenta il potere fisico e il potere magico.",
    "Increases your chance to land a critical hit.": "Aumenta la probabilità di mettere a segno un colpo critico.",
    "Increases the bonus damage dealt by critical hits.": "Aumenta il danno aggiuntivo dei colpi critici.",
    "Increases the slow applied by Chill.": "Aumenta il rallentamento applicato dal gelo.",
    "Increases the damage dealt by Poison.": "Aumenta il danno inflitto dal veleno.",
    "Increases the damage dealt by Burning.": "Aumenta il danno inflitto dall'ustione.",
    "Increases the damage dealt by Bleeding.": "Aumenta il danno inflitto dal sanguinamento.",
    "Increases the duration of Rage stacks.": "Aumenta la durata delle cariche di furia.",
    "Increases the duration of Chill stacks.": "Aumenta la durata delle cariche di gelo.",
    "Increases the duration of Poison stacks.": "Aumenta la durata delle cariche di veleno.",
    "Increases the duration of Burning stacks.": "Aumenta la durata delle cariche di ustione.",
    "Increases the duration of Bleeding stacks.": "Aumenta la durata delle cariche di sanguinamento.",
    "Increases the maximum Rage stacks you can gain.": "Aumenta le cariche massime di furia che puoi accumulare.",
    "Increases the maximum Chill stacks you can apply.": "Aumenta le cariche massime di gelo che puoi applicare.",
    "Increases the maximum Shock stacks you can apply.": "Aumenta le cariche massime di scossa che puoi applicare.",
    "Increases the maximum Poison stacks you can apply.": "Aumenta le cariche massime di veleno che puoi applicare.",
    "Increases the maximum Burning stacks you can apply.": "Aumenta le cariche massime di ustione che puoi applicare.",
    "Increases the maximum Bleeding stacks you can apply.": "Aumenta le cariche massime di sanguinamento che puoi applicare.",
    "Increases all Fire Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno da fuoco che infliggi.",
    "Increases all Ice Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno da ghiaccio che infliggi.",
    "Increases all Blunt Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno contundente che infliggi.",
    "Increases all Decay Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno da decadimento che infliggi.",
    "Increases all Ether Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno da etere che infliggi.",
    "Increases all Strike Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno da taglio che infliggi.",
    "Increases all Thrust Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno perforante che infliggi.",
    "Increases all Electricity Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno da elettricità che infliggi.",
    "Increases all Strike, Thrust, and Blunt Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno da taglio, perforante e contundente che infliggi.",
    "Increases all Fire, Ice, Electricity, Decay, and Ether Damage you deal by a percentage.": "Aumenta di una percentuale tutto il danno da fuoco, ghiaccio, elettricità, decadimento ed etere che infliggi.",
    "Increases the Stun Build-up your attacks and effects deal.": "Aumenta l'accumulo di stordimento dei tuoi attacchi ed effetti.",
    "Increases the Concentration you restore when hitting enemies.": "Aumenta la concentrazione che recuperi colpendo i nemici.",
    "Increases the Concentration you restore from Concentration on Hit by a percentage.": "Aumenta di una percentuale la concentrazione recuperata dalla concentrazione al colpo.",
    "Increases Concentration, letting you cast more spells before running out.": "Aumenta la concentrazione, permettendoti di lanciare più incantesimi prima di esaurirla.",
    "Increases concentration, enabling the player to cast spell more efficiently.": "Aumenta la concentrazione, permettendo di lanciare incantesimi in modo più efficiente.",
    "Increases maximum Stamina, supporting sprinting and stamina-based abilities.": "Aumenta il vigore massimo, sostenendo lo scatto e le abilità che consumano vigore.",
    "Increases how much weight you can carry before becoming encumbered.": "Aumenta il peso che puoi trasportare prima di essere ingombrato.",
    "Increases the speed of your basic attack combo (does not affect skills).": "Aumenta la velocità della combo di attacco base (non influisce sulle abilità).",
    "Increases damage for all spells and abilities that deal Strike, Thrust, or Blunt Damage.": "Aumenta il danno di tutti gli incantesimi e le abilità che infliggono danno da taglio, perforante o contundente.",
    "Increases damage for all spells and abilities that deal Fire, Ice, Electricity, Decay, or Ether Damage.": "Aumenta il danno di tutti gli incantesimi e le abilità che infliggono danno da fuoco, ghiaccio, elettricità, decadimento o etere.",
    "Increases your critical hit chance against Burning targets.": "Aumenta la probabilità di critico contro bersagli ustionati.",
    "Increases your critical hit chance against Chilled targets.": "Aumenta la probabilità di critico contro bersagli assiderati.",
    "Increases your critical hit chance against Stunned targets.": "Aumenta la probabilità di critico contro bersagli storditi.",
    "Increases your critical hit chance against Bleeding targets.": "Aumenta la probabilità di critico contro bersagli sanguinanti.",
    "Increases your critical hit chance against Poisoned targets.": "Aumenta la probabilità di critico contro bersagli avvelenati.",
    "Increases your critical hit damage against Burning targets.": "Aumenta il danno critico contro bersagli ustionati.",
    "Increases your critical hit damage against Chilled targets.": "Aumenta il danno critico contro bersagli assiderati.",
    "Increases your critical hit damage against Stunned targets.": "Aumenta il danno critico contro bersagli storditi.",
    "Increases your critical hit damage against Bleeding targets.": "Aumenta il danno critico contro bersagli sanguinanti.",
    "Increases your critical hit damage against Poisoned targets.": "Aumenta il danno critico contro bersagli avvelenati.",
    "Deal increased damage to Chilled targets.": "Infliggi più danno ai bersagli assiderati.",
    "Deal increased damage to Stunned targets.": "Infliggi più danno ai bersagli storditi.",
    "Deal increased damage to targets at full Health.": "Infliggi più danno ai bersagli con salute piena.",
    "Deal increased damage to targets below 40% Health.": "Infliggi più danno ai bersagli sotto il 40% di salute.",
    "Deal increased damage to targets that are Burning.": "Infliggi più danno ai bersagli ustionati.",
    "Deal increased damage to targets that are Bleeding.": "Infliggi più danno ai bersagli sanguinanti.",
    "Deal increased damage to targets that are Poisoned.": "Infliggi più danno ai bersagli avvelenati.",
    "Deal less damage, but double the burning stacks": "Infliggi meno danno, ma raddoppia le cariche di ustione",
    "Reduces spell cooldowns. Less effective at higher values.": "Riduce i tempi di recupero degli incantesimi. Meno efficace ai valori alti.",
    "Reduces Ice Damage taken. Less effective at higher values.": "Riduce il danno da ghiaccio subito. Meno efficace ai valori alti.",
    "Reduces Fire Damage taken. Less effective at higher values.": "Riduce il danno da fuoco subito. Meno efficace ai valori alti.",
    "Reduces Blunt Damage taken. Less effective at higher values.": "Riduce il danno contundente subito. Meno efficace ai valori alti.",
    "Reduces Decay Damage taken. Less effective at higher values.": "Riduce il danno da decadimento subito. Meno efficace ai valori alti.",
    "Reduces Ether Damage taken. Less effective at higher values.": "Riduce il danno da etere subito. Meno efficace ai valori alti.",
    "Reduces Thrust Damage taken. Less effective at higher values.": "Riduce il danno perforante subito. Meno efficace ai valori alti.",
    "Reduces Strike Damage taken. Less effective at higher values.": "Riduce il danno da taglio subito. Meno efficace ai valori alti.",
    "Reduces Electricity Damage taken. Less effective at higher values.": "Riduce il danno da elettricità subito. Meno efficace ai valori alti.",
    "Reduces the Stamina damage you take while blocking by a percentage.": "Riduce di una percentuale il danno al vigore che subisci parando.",
    "Causes your damage to ignore a portion of the target's Armor.": "Fa sì che il tuo danno ignori una parte dell'armatura del bersaglio.",
    "Causes your damage to ignore a percentage of the target's Armor.": "Fa sì che il tuo danno ignori una percentuale dell'armatura del bersaglio.",
    "Causes your damage to ignore a portion of the target's Resistance.": "Fa sì che il tuo danno ignori una parte della resistenza del bersaglio.",
    "Causes your damage to ignore a percentage of the target's Resistance.": "Fa sì che il tuo danno ignori una percentuale della resistenza del bersaglio.",
    "Causes your Physical Damage to ignore a portion of the target's Armor.": "Fa sì che il tuo danno fisico ignori una parte dell'armatura del bersaglio.",
    "Causes your Magic Damage to ignore a portion of the target's Resistance.": "Fa sì che il tuo danno magico ignori una parte della resistenza del bersaglio.",
    "Causes your Blunt Damage to ignore a portion of the target's Blunt Armor.": "Fa sì che il tuo danno contundente ignori una parte dell'armatura contundente del bersaglio.",
    "Causes your Strike Damage to ignore a portion of the target's Strike Armor.": "Fa sì che il tuo danno da taglio ignori una parte dell'armatura da taglio del bersaglio.",
    "Causes your Thrust Damage to ignore a portion of the target's Thrust Armor.": "Fa sì che il tuo danno perforante ignori una parte dell'armatura perforante del bersaglio.",
    "Causes your Ice Damage to ignore a portion of the target's Ice Resistance.": "Fa sì che il tuo danno da ghiaccio ignori una parte della resistenza al ghiaccio del bersaglio.",
    "Causes your Fire Damage to ignore a portion of the target's Fire Resistance.": "Fa sì che il tuo danno da fuoco ignori una parte della resistenza al fuoco del bersaglio.",
    "Causes your Decay Damage to ignore a portion of the target's Decay Resistance.": "Fa sì che il tuo danno da decadimento ignori una parte della resistenza al decadimento del bersaglio.",
    "Causes your Ether Damage to ignore a portion of the target's Ether Resistance.": "Fa sì che il tuo danno da etere ignori una parte della resistenza all'etere del bersaglio.",
    "Causes your Electricity Damage to ignore a portion of the target's Electricity Resistance.": "Fa sì che il tuo danno da elettricità ignori una parte della resistenza all'elettricità del bersaglio.",
    "Causes your Poison & Decay Damage to ignore a portion of the target's Decay Resistance.": "Fa sì che il tuo danno da veleno e decadimento ignori una parte della resistenza al decadimento del bersaglio.",
    "Increases your Armor, reducing Physical Damage taken and stacking with damage-type defenses. Less effective at higher values.": "Aumenta la tua armatura, riducendo il danno fisico subito e sommandosi alle difese per tipo di danno. Meno efficace ai valori alti.",
    "Increases your Resistance, reducing Magic Damage taken and stacking with damage-type defenses. Less effective at higher values.": "Aumenta la tua resistenza, riducendo il danno magico subito e sommandosi alle difese per tipo di danno. Meno efficace ai valori alti.",
    "A percent bonus applied to all damage you deal, added together with your other percent bonuses.": "Un bonus percentuale applicato a tutto il danno che infliggi, sommato agli altri bonus percentuali.",
    "Passive bonus - stacks with your other bonuses.": "Bonus passivo: si somma agli altri bonus.",
    "Active effect - only the strongest instance applies.": "Effetto attivo: vale solo l'istanza più forte.",
    "Your maximum Concentration. Used as a resource for certain abilities and effects.": "La tua concentrazione massima. Usata come risorsa da alcune abilità ed effetti.",
    "Experience points needed for next level.": "Punti esperienza necessari per il livello successivo.",
    "Max encumbrance increased. You can carry more.": "Ingombro massimo aumentato. Puoi trasportare di più.",
    "Health is your total hitpoints. It regenerates when you're out of combat. If your Hunger meter is low, it limits how much Health you can recover until you eat.": "La salute rappresenta i tuoi punti vita totali. Si rigenera fuori dal combattimento. Se l'indicatore della fame è basso, limita la salute che puoi recuperare finché non mangi.",
    "Stamina is used for running, dodging, attacking, and casting spells. It regenerates quickly. If your Thirst meter is low, it limits how much Stamina you can recover until you drink.": "Il vigore serve per correre, schivare, attaccare e lanciare incantesimi. Si rigenera rapidamente. Se l'indicatore della sete è basso, limita il vigore che puoi recuperare finché non bevi.",
    "Concentration is needed to cast spells. It regenerates when you land basic attacks or when you're out of combat. If your Thirst meter is low, it limits how much Concentration you can recover until you drink.": "La concentrazione serve per lanciare incantesimi. Si rigenera colpendo con gli attacchi base o fuori dal combattimento. Se l'indicatore della sete è basso, limita la concentrazione che puoi recuperare finché non bevi.",

    # ---- statistiche con due punti ----------------------------------------
    "Electricity Piercing:": "Penetrazione da elettricità:",
    "Electricity Resistance:": "Resistenza all'elettricità:",
    "Magic Damage Percent:": "Danno magico %:",
    "Physical Damage Percent:": "Danno fisico %:",
    "Concentration Percent:": "Concentrazione %:",
    "Resistance Penetration:": "Penetrazione delle resistenze:",
    "Resistance Penetration Percent:": "Penetrazione delle resistenze %:",
    "Armor Penetration Percent:": "Penetrazione dell'armatura %:",
    "Damage vs. Low Health:": "Danno vs. salute bassa:",
    "Damage vs. Full Health:": "Danno vs. salute massima:",
    "Critical Chance vs. Poison:": "Probabilità di critico vs. veleno:",
    "Critical Damage vs. Poison:": "Danno critico vs. veleno:",
    "Critical Chance vs. Burning:": "Probabilità di critico vs. ustione:",
    "Critical Chance vs. Chilled:": "Probabilità di critico vs. assiderato:",
    "Critical Chance vs. Stunned:": "Probabilità di critico vs. stordito:",
    "Critical Chance vs. Bleeding:": "Probabilità di critico vs. sanguinamento:",
    "Critical Damage vs. Burning:": "Danno critico vs. ustione:",
    "Critical Damage vs. Stunned:": "Danno critico vs. stordito:",
    "Critical Damage vs. Bleeding:": "Danno critico vs. sanguinamento:",
    "Stun Buildup Increase:": "Aumento accumulo stordimento:",
    "Concentration Regeneration": "Rigenerazione della concentrazione",

    # ---- impostazioni e opzioni -------------------------------------------
    "Display/Hide Tooltips": "Mostra/nascondi le descrizioni",
    "Display/Hide Item Tooltips": "Mostra/nascondi le descrizioni oggetti",
    "Toggle Stats Dropdown": "Apri/chiudi l'elenco delle statistiche",
    "Show/Hide Filter Menu": "Mostra/nascondi il menu dei filtri",
    "Hold for Salvage Mode": "Tieni premuto per la modalità recupero",
    "Lock Camera to Player": "Blocca la telecamera sul giocatore",
    "Camera Panning Dead Zone": "Zona morta del movimento telecamera",
    "Retarget While Casting": "Cambia bersaglio durante il lancio",
    "Toggle Break Equipment": "Attiva/disattiva rottura equipaggiamento",
    "Show Party Indicators": "Mostra gli indicatori del gruppo",
    "Show Full Party Vitals": "Mostra tutti i vitali del gruppo",
    "Show Map Marker Indicators": "Mostra gli indicatori dei segnalini",
    "Show Other Players Damage": "Mostra il danno degli altri giocatori",
    "Show Spell Indicators During Cast": "Mostra gli indicatori durante il lancio",
    "Share Waygate Unlocks": "Condividi i Varchi sbloccati",
    "Lock Buildings to Owner": "Blocca le costruzioni al proprietario",
    "Random Recipe Discovery": "Scoperta casuale delle ricette",
    "Auto Sprint While Exploring": "Scatto automatico in esplorazione",
    "Auto Sprint Outside Of Combat ": "Scatto automatico fuori dal combattimento ",
    "Nearby Event Advanced": "Evento vicino avanzato",
    "Salvage directly in inventory": "Recupera direttamente nell'inventario",
    "Transfer All to Inventory": "Trasferisci tutto nell'inventario",
    "Stop Current Item In Queue": "Interrompi l'oggetto in coda",
    "Super Ultra Wide (1440p)": "Super ultrapanoramico (1440p)",
    "Enable Steam Deck Back Grip Buttons": "Attiva i tasti posteriori di Steam Deck",
    "To use this feature, you must bind the back grip buttons on your steam deck to F5 through F8": "Per usare questa funzione devi assegnare i tasti posteriori dello Steam Deck da F5 a F8",
    "This setting cannot be re-enabled once disabled. Are you sure you want to continue?": "Questa impostazione non può essere riattivata una volta disattivata. Vuoi continuare?",
    "Can be changed anytime from the Settings menu": "Modificabile in qualsiasi momento dal menu Impostazioni",
    "Only its owner can change this.": "Solo il proprietario può modificarlo.",
    "Select a movement type": "Seleziona un tipo di movimento",
    "Manual sprint during exploration and combat. \\nHold the sprint input to sprint. \\n<i> <color=#FFDA00>Sprint costs Stamina only during combat.</color> </i>": "Scatto manuale in esplorazione e in combattimento. \\nTieni premuto il comando per scattare. \\n<i> <color=#FFDA00>Lo scatto consuma vigore solo in combattimento.</color> </i>",
    "Automatically sprint during exploration. \\nManually sprint during combat.\\nHold the sprint input to sprint. \\n<i> <color=#FFDA00>Sprint costs Stamina only during combat.</color> </i>": "Scatto automatico in esplorazione. \\nScatto manuale in combattimento.\\nTieni premuto il comando per scattare. \\n<i> <color=#FFDA00>Lo scatto consuma vigore solo in combattimento.</color> </i>",

    # ---- messaggi di gioco -------------------------------------------------
    "Combat items refilled": "Oggetti da combattimento ricaricati",
    "This item can be refilled by resting at a campfire": "Questo oggetto si ricarica riposando presso un falò",
    "Rest at a campfire to refill combat items": "Riposa presso un falò per ricaricare gli oggetti da combattimento",
    "You are Incapacitated!": "Sei incapacitato!",
    "You are currently in combat": "Sei in combattimento",
    "Cannot use backpack in combat": "Non puoi usare lo zaino in combattimento",
    "You slept until {0}:00": "Hai dormito fino alle {0}:00",
    "Waiting for player to sleep": "In attesa che il giocatore dorma",
    "{0} has begun to rest": "{0} ha iniziato a riposare",
    "{0} has begun to sleep": "{0} ha iniziato a dormire",
    "{0} is requesting to make rest": "{0} chiede di riposare",
    "Wait for revival or hold ": "Attendi la rianimazione o tieni premuto ",
    "to revive at the nearest waypoint.": "per rianimarti al punto di passaggio più vicino.",
    "You are getting hungry. Health is reduced.": "Stai diventando affamato. La salute è ridotta.",
    "You feel thirsty. Stamina and concentration are reduced.": "Hai sete. Vigore e concentrazione sono ridotti.",
    "Your nourishment is low. Regeneration is reduced.": "Il tuo nutrimento è basso. La rigenerazione è ridotta.",
    "Sent {0} items to {1}": "Inviati {0} oggetti a {1}",
    "{0} shown / {1} found": "{0} mostrati / {1} trovati",
    "Nothing discovered yet": "Nessuna scoperta ancora",
    "No entries match your search.": "Nessuna voce corrisponde alla ricerca.",
    "No items in this filter": "Nessun oggetto in questo filtro",
    "This belongs to another player.": "Questo appartiene a un altro giocatore.",
    "That stack is already fully selected": "Quella pila è già selezionata per intero",
    "All selection slots are full": "Tutti gli slot di selezione sono pieni",
    "Selection changed. Pick your recipe items again": "Selezione cambiata. Scegli di nuovo gli oggetti della ricetta",
    "Only recipe items can be selected": "Si possono selezionare solo oggetti da ricetta",
    "Only recipe items from your backpack can be selected": "Si possono selezionare solo oggetti da ricetta dello zaino",
    "Select at least {0} duplicate recipe items": "Seleziona almeno {0} oggetti da ricetta duplicati",
    "Insufficient ingredient quantity!": "Quantità di ingredienti insufficiente!",
    "This recipe requires: {0}": "Questa ricetta richiede: {0}",
    "Requires crafting level {0}": "Richiede livello di artigianato {0}",
    "Recipe Already Learned": "Ricetta già appresa",
    "Recipe is for another bench": "La ricetta è per un altro banco",
    "No recipes to unlock.": "Nessuna ricetta da sbloccare.",
    "New Recipe Unlocked: {0}": "Nuova ricetta sbloccata: {0}",
    "One ingredient away from a new recipe!": "Manca un ingrediente per una nuova ricetta!",
    "One ingredient away from {0} new recipes!": "Manca un ingrediente per {0} nuove ricette!",
    "That item does not teach a craftable recipe": "Quell'oggetto non insegna una ricetta realizzabile",
    "You haven't learned this recipe yet. Use the item instead": "Non hai ancora appreso questa ricetta. Usa invece l'oggetto",
    "Alchemy Table Required": "Richiede un tavolo d'alchimia",
    "Woodfire Stove Required": "Richiede una stufa a legna",
    "Send everything in the container to your inventory": "Invia tutto il contenuto nel tuo inventario",
    "Anyone can spend what is stored here on their builds and crafts.": "Chiunque può usare quanto è depositato qui per costruzioni e manufatti.",
    "Only you can spend what is stored here on your builds and crafts.": "Solo tu puoi usare quanto è depositato qui per le tue costruzioni e manufatti.",
    "Items in chests you can access are counted alongside your backpack, and are spent automatically.": "Gli oggetti nelle casse accessibili vengono contati insieme allo zaino e usati automaticamente.",
    "Only your backpack is being counted. Place a chest, or set one to public, and its contents count too.": "Viene contato solo lo zaino. Piazza una cassa, o rendine una pubblica, e conterà anche il suo contenuto.",
    "A workstation or production building is supplying you too.": "Anche una postazione o un edificio di produzione ti rifornisce.",
    "{0} workstations and production buildings are supplying you too.": "Anche {0} postazioni ed edifici di produzione ti riforniscono.",
    "Pulling from {0} chests": "Prelievo da {0} casse",
    "No special modifiers.": "Nessun modificatore speciale.",
    "Are you sure of your choices?": "Sei sicuro delle tue scelte?",
    "Are you sure you want to delete this world?": "Vuoi davvero eliminare questo mondo?",
    "Are you sure you want to delete this character?": "Vuoi davvero eliminare questo personaggio?",
    "Are you sure you want to disconnect from lobby?": "Vuoi davvero disconnetterti dalla lobby?",
    "Are you sure you want to sell your beloved pet?": "Vuoi davvero vendere il tuo amato compagno?",
    "Are you sure you want to shatter your equipped item?": "Vuoi davvero frantumare l'oggetto equipaggiato?",
    "Save failed: returning to main menu to protect your progress.": "Salvataggio fallito: ritorno al menu principale per proteggere i tuoi progressi.",
    "Nearby Event Complete!": "Evento vicino completato!",
    "Codex Updated: New entries available": "Codex aggiornato: nuove voci disponibili",
    "Codex: Empowered Monster information discovered.": "Codex: scoperte informazioni sui mostri potenziati.",
    "New deeds available at the deed board.": "Nuovi incarichi disponibili alla bacheca.",
    "Poker Table unlocked! You can now build one at your base.": "Tavolo da poker sbloccato! Ora puoi costruirne uno alla base.",
    "Befr accepted your junk for {0}g": "Befr ha accettato la tua robaccia per {0}g",
    "Available Skill Points": "Punti abilità disponibili",
    "Earlwood Village South": "Villaggio di Earlwood Sud",
    "The Traveling Merchant": "Il mercante ambulante",
    "Equipment Upgrade Overview": "Riepilogo dei miglioramenti",
    "Rune essence gain: +10% Coarse & Shaped": "Guadagno essenza runica: +10% grezza e modellata",
    "Rune essence gain: +20% Coarse & Shaped": "Guadagno essenza runica: +20% grezza e modellata",
    "Pet Pen: 12 slots, train pets to level 10, +10% pen XP.": "Recinto: 12 posti, allena i compagni fino al livello 10, +10% XP del recinto.",
    "Pet Pen: 24 slots, train pets to level 15, +20% pen XP.": "Recinto: 24 posti, allena i compagni fino al livello 15, +20% XP del recinto.",
    "Pet Spell Description": "Descrizione dell'incantesimo del compagno",
    "Wanting to lighten your load? Pets can run back to town and sell your gear for you.": "Vuoi alleggerire il carico? I compagni possono tornare in città e vendere la tua attrezzatura per te.",
    "Upgrade Manga to gain more rune essence when salvaging runes.": "Migliora Manga per ottenere più essenza runica recuperando le rune.",
    "Upgrade Heimen's stage to unlock more music for his music box.": "Migliora il palco di Heimen per sbloccare più musica per il suo carillon.",
    "Build up Heimen's dwelling to access new songs.": "Amplia la dimora di Heimen per accedere a nuovi brani.",
    "Upgrade Basilton to expand how many farm plots you can place at your base.": "Migliora Basilton per aumentare il numero di appezzamenti che puoi piazzare.",
    "Expands your farm plot limit to 40. Basilton sells Tenderberry and Thaumablossom seeds.": "Porta il limite di appezzamenti a 40. Basilton vende semi di Tenderberry e Thaumablossom.",
    "Expands your farm plot limit to 60. Basilton sells Emberbloom and Singing Bellflower seeds.": "Porta il limite di appezzamenti a 60. Basilton vende semi di Emberbloom e Campanula Canterina.",
    "Saqi serves premium feasts and resistance dishes.": "Saqi serve banchetti pregiati e piatti che donano resistenza.",
    "Saqi serves hearty stove dishes and specialist drinks.": "Saqi serve piatti sostanziosi da stufa e bevande speciali.",
    "Upgrade Saqi to expand her menu of crafted meals.": "Migliora Saqi per ampliare il suo menu di pasti preparati.",
    "Befr stocks stone tools, lesser potions, basic crafting recipes, and the stone building set of foundations, walls and fences.": "Befr vende strumenti in pietra, pozioni minori, ricette base e il set costruttivo in pietra di fondazioni, muri e recinti.",
    "Befr stocks copper tools, advanced alchemy and throwable recipes, and the heartwood building set of foundations, walls and fences.": "Befr vende strumenti in rame, ricette avanzate di alchimia e da lancio, e il set costruttivo in durame di fondazioni, muri e recinti.",
    "Rebuild the Earlwood Bridge": "Ricostruisci il ponte di Earlwood",
    "Build a hanging bridge to cross the gap.": "Costruisci un ponte sospeso per superare il dirupo.",
    "Charge forward. Deals Blunt damage to the first enemy hit. Damage increases with distance traveled.": "Carica in avanti. Infligge danno contundente al primo nemico colpito. Il danno aumenta con la distanza percorsa.",
    "Cast spell to deal <i><color=#FF7A00>fire damage</color></i> in an area around you.": "Lancia l'incantesimo per infliggere <i><color=#FF7A00>danno da fuoco</color></i> in un'area attorno a te.",

    # ---- tutorial e suggerimenti ------------------------------------------
    "Walk up to the chest and press": "Avvicinati alla cassa e premi",
    "to interact and collect the items": "per interagire e raccogliere gli oggetti",
    "and <color=#FFDA00>hold</color>": "e <color=#FFDA00>tieni premuto</color>",
    "To <color=#FFDA00>run</color> hold": "Per <color=#FFDA00>correre</color> tieni premuto",
    "To <color=#FFDA00>block</color> hold": "Per <color=#FFDA00>parare</color> tieni premuto",
    "To <color=#FFDA00>block</color> press ": "Per <color=#FFDA00>parare</color> premi ",
    "To <color=#FFDA00>dash</color> press": "Per <color=#FFDA00>scattare</color> premi",
    "To <color=#FFDA00>attack</color> press ": "Per <color=#FFDA00>attaccare</color> premi ",
    "To <color=#FFDA00>lock the target</color> press ": "Per <color=#FFDA00>bloccare il bersaglio</color> premi ",
    "<color=#FFDA00>Move</color> around with": "<color=#FFDA00>Muoviti</color> con",
    "Open your <color=#FFDA00>Inventory</color>": "Apri l'<color=#FFDA00>inventario</color>",
    "Open your <color=#FFDA00>Map </color> at any time by <color=#FFDA00>pressing </color>": "Apri la <color=#FFDA00>mappa </color> in qualsiasi momento <color=#FFDA00>premendo </color>",
    "Open <color=#FFDA00>Build Menu</color> by holding": "Apri il <color=#FFDA00>menu costruzioni</color> tenendo premuto",
    "Open <color=#FFDA00>Build Menu</color> by pressing": "Apri il <color=#FFDA00>menu costruzioni</color> premendo",
    "then <color=#FFDA00>drag</color> a piece of <color=#FFDA00>equipment</color> into the": "poi <color=#FFDA00>trascina</color> un pezzo di <color=#FFDA00>equipaggiamento</color> nello",
    "<color=#FFDA00>appropriate equipment slot</color> to equip it.": "<color=#FFDA00>slot appropriato</color> per equipaggiarlo.",
    "then <color=#FFDA00>dismantle</color> a building by <color=#FFDA00>selecting</color> it with the": "poi <color=#FFDA00>smonta</color> una costruzione <color=#FFDA00>selezionandola</color> con il",
    "then <color=#FFDA00>dismantle</color> a building by <color=#FFDA00>hover</color> and <color=#FFDA00>hold</color>": "poi <color=#FFDA00>smonta</color> una costruzione <color=#FFDA00>passandoci sopra</color> e <color=#FFDA00>tenendo premuto</color>",
    "You can <color=#FFDA00>craft</color> in your <color=#FFDA00>backpack</color> by pressing": "Puoi <color=#FFDA00>creare</color> nello <color=#FFDA00>zaino</color> premendo",
    "Equip <color=#FFDA00>Consumables</color> to your <color=#FFDA00>Hot bar</color>": "Assegna i <color=#FFDA00>consumabili</color> alla <color=#FFDA00>barra rapida</color>",
    "Equip <color=#FFDA00>multiple pieces</color> from the same set to activate a powerful <color=#FFDA00>set bonus!</color>": "Equipaggia <color=#FFDA00>più pezzi</color> dello stesso set per attivare un potente <color=#FFDA00>bonus del set!</color>",
    "Some items, like <color=#FFDA00>potions</color>, can be <color=#FFDA00>equipped</color> to your <color=#FFDA00>Hot bar</color> for quick use during <color=#FFDA00>combat</color>.": "Alcuni oggetti, come le <color=#FFDA00>pozioni</color>, possono essere <color=#FFDA00>assegnati</color> alla <color=#FFDA00>barra rapida</color> per l'uso immediato in <color=#FFDA00>combattimento</color>.",
    "Stay <color=#FFDA00>Fed</color> and <color=#FFDA00>Hydrated</color>.": "Resta <color=#FFDA00>sazio</color> e <color=#FFDA00>idratato</color>.",
    "Remember to <color=#FFDA00>eat</color> and <color=#FFDA00>drink</color> regularly.": "Ricorda di <color=#FFDA00>mangiare</color> e <color=#FFDA00>bere</color> regolarmente.",
    "If you don't, your maximum <color=#FFDA00>Health,</color> ": "Altrimenti la tua <color=#FFDA00>salute</color> massima, ",
    "<color=#FFDA00>Concentration,</color> and <color=#FFDA00>Stamina</color> will decrease.": "la <color=#FFDA00>concentrazione</color> e il <color=#FFDA00>vigore</color> caleranno.",
    "Use <color=#FFDA00>Map Crystals</color> to fill in your Map.": "Usa i <color=#FFDA00>cristalli di mappa</color> per completare la mappa.",
    "for the power of the emoji": "per il potere delle emoji",
    "You can press Spacebar to dash and hold Space bar to Run faster": "Premi la barra spaziatrice per scattare e tienila premuta per correre più veloce",
    "You can press the Spacebar to dash, and hold it down to run faster.": "Premi la barra spaziatrice per scattare e tienila premuta per correre più veloce.",
    "You can use the Waygate to reach your destination more quickly.": "Puoi usare il Varco per raggiungere la destinazione più rapidamente.",
    "You can upgrade your equipment at the Forge to make items stronger.": "Puoi migliorare l'equipaggiamento alla Fucina per rendere gli oggetti più forti.",
    "You have enough XP to level up!\\n Find a Trainer or Campfire to Train.": "Hai abbastanza XP per salire di livello!\\n Trova un addestratore o un falò per allenarti.",

    # ---- gruppo, server, lobby --------------------------------------------
    "{0} has left the party": "{0} ha lasciato il gruppo",
    "{0} has joined the party": "{0} si è unito al gruppo",
    "{0} has joined the server": "{0} è entrato nel server",
    "{0} has been kicked from the party": "{0} è stato espulso dal gruppo",
    "You have been kicked from the party": "Sei stato espulso dal gruppo",
    "You have been invited to join party: {0}": "Sei stato invitato a unirti al gruppo: {0}",
    "{0} is now the party leader": "{0} è ora il capogruppo",
    "You must be in a party to leave": "Devi essere in un gruppo per uscirne",
    "You must be in a party to be a leader": "Devi essere in un gruppo per esserne il capo",
    "You must be invited to a party": "Devi essere invitato a un gruppo",
    "You must leave your current party first": "Devi prima lasciare il gruppo attuale",
    "You must be the party leader to disband a party": "Devi essere il capogruppo per scioglierlo",
    "You must be the party leader to transfer party ownership": "Devi essere il capogruppo per trasferirne la proprietà",
    "Only the party leader can kick players": "Solo il capogruppo può espellere giocatori",
    "Your party is already at the maximum size": "Il tuo gruppo ha già raggiunto la dimensione massima",
    "That party name is already taken": "Quel nome di gruppo è già in uso",
    "That player is not in this party": "Quel giocatore non è in questo gruppo",
    "That player is not in your party": "Quel giocatore non è nel tuo gruppo",
    "That player is already in a party": "Quel giocatore è già in un gruppo",
    "That player is already in your party": "Quel giocatore è già nel tuo gruppo",
    "You've already recently invited that player": "Hai già invitato quel giocatore di recente",
    "Could not find a player with that name": "Nessun giocatore trovato con quel nome",
    "{0} wants to defend {1}": "{0} vuole difendere {1}",
    "{0} wants to harvest {1}": "{0} vuole raccogliere {1}",
    "{0} wants to talk to {1}": "{0} vuole parlare con {1}",
    "{0} wants help attacking {1}": "{0} chiede aiuto per attaccare {1}",
    "{0} wants someone to pick up {1}": "{0} chiede a qualcuno di raccogliere {1}",
    "{0} is asking for support": "{0} chiede supporto",
    "{0} is playing on {1} mode": "{0} sta giocando in modalità {1}",
    "Searching for lobbies...": "Ricerca delle lobby...",
    "Unable to fetch lobbies.": "Impossibile recuperare le lobby.",
    "No lobbies match your filters.": "Nessuna lobby corrisponde ai filtri.",
    "Lobby browser unavailable in direct connect mode.": "Elenco lobby non disponibile in connessione diretta.",
    "Back to Lobby Selection": "Torna alla scelta della lobby",
    "Back to World Selection": "Torna alla scelta del mondo",
    "Waiting for another player to join...": "In attesa di un altro giocatore...",
    "Server is running a different version": "Il server usa una versione diversa",
    "Steam is not available.": "Steam non è disponibile.",
    "Could not open the password prompt": "Impossibile aprire la richiesta della password",
    "incompatible difficulty level": "livello di difficoltà incompatibile",
    "All Characters Allowed": "Tutti i personaggi ammessi",
    "This world accepts new characters only": "Questo mondo accetta solo nuovi personaggi",
    "More than 8 Players is not officially supported": "Più di 8 giocatori non è ufficialmente supportato",
    "Adjust Difficulty Level": "Regola il livello di difficoltà",
    "The playtest is currently unavailable.\\nStay updated on the latest playtest news by going to:": "Il playtest non è attualmente disponibile.\\nPer restare aggiornato sulle novità del playtest vai su:",
    "This server hosts an unstable mix of prototypes, half-baked ideas, and code that somehow works. Expect strange behavior, broken features, and occasional brilliance. Perfect for testing, terrible for production.": "Questo server ospita un misto instabile di prototipi, idee abbozzate e codice che in qualche modo funziona. Aspettati comportamenti strani, funzioni rotte e qualche lampo di genio. Perfetto per i test, terribile per la produzione.",

    # ---- poker -------------------------------------------------------------
    "{0} raised {1} chips.": "{0} ha rilanciato di {1} fiche.",
    "{0} went all-in with {1} chips.": "{0} è andato all-in con {1} fiche.",
    "{0} ran out of time and folds.": "{0} ha esaurito il tempo e passa.",
    "{0}'s hand was folded automatically.": "La mano di {0} è stata passata automaticamente.",
    "{0} ran out of chips and is sitting out.": "{0} ha esaurito le fiche e salta il turno.",
    "{0} ran out of chips and left the table.": "{0} ha esaurito le fiche e ha lasciato il tavolo.",
    "{0} wins the pot of {1} with {2}.": "{0} vince il piatto di {1} con {2}.",
    "{0} wins the main pot of {1}.": "{0} vince il piatto principale di {1}.",
    "{0} wins a side pot of {1} with {2}.": "{0} vince un piatto laterale di {1} con {2}.",
    "{0} tie for the pot of {1}! Each receives {2}.": "{0} pareggiano per il piatto di {1}! Ognuno riceve {2}.",
    "No one is eligible for the pot of {0}. It is forfeited.": "Nessuno ha diritto al piatto di {0}. Viene perso.",
    "{0} is now the big blind.": "{0} è ora il buio grande.",
    "{0} is now the small blind.": "{0} è ora il buio piccolo.",
    "No active player can post the big blind.": "Nessun giocatore attivo può versare il buio grande.",
    "No active player can post the small blind.": "Nessun giocatore attivo può versare il buio piccolo.",
    "No active player can take the dealer button.": "Nessun giocatore attivo può prendere il bottone del mazziere.",
    "No player is able to act first.": "Nessun giocatore può agire per primo.",
    "Only one player remains. The round is over.": "Resta un solo giocatore. Il turno è finito.",
    "The first hand begins in {0} seconds...": "La prima mano inizia in {0} secondi...",
    "Countdown complete. Dealing the first hand!": "Conto alla rovescia finito. Si distribuisce la prima mano!",
    "Countdown cancelled: fewer than two players remain.": "Conto alla rovescia annullato: restano meno di due giocatori.",
    "{0} has joined the table in seat {1}.": "{0} si è unito al tavolo al posto {1}.",
    "{0} cannot sit in (not enough gold).": "{0} non può entrare (oro insufficiente).",
    "{0} is sitting out (not enough gold for the buy-in).": "{0} salta il turno (oro insufficiente per l'ingresso).",
    "No seats are available at this table.": "Non ci sono posti liberi a questo tavolo.",
    "No seats are available at this table for an NPC.": "Non ci sono posti liberi a questo tavolo per un NPC.",
    "100G buy-in required to play": "Serve un ingresso da 100G per giocare",
    "Royal Flush: A, K, Q, J, 10 of the same suit.": "Scala Reale Massima: A, K, Q, J, 10 dello stesso seme.",
    "Straight Flush: Five consecutive cards of the same suit (e.g., 8, 9, 10, J, Q of hearts).": "Scala Reale: cinque carte consecutive dello stesso seme (es. 8, 9, 10, J, Q di cuori).",
    "Having the best hand at the showdown.\\nMaking all other players fold during betting.": "Avere la mano migliore allo showdown.\\nFar passare tutti gli altri giocatori durante le puntate.",
    "The Deal: Each player is dealt 2 cards\\nBetting Rounds: Players take turns betting, calling, raising, or folding.\\nWinning the Hand: The pot is won by:\\n": "La distribuzione: ogni giocatore riceve 2 carte\\nGiri di puntata: i giocatori a turno puntano, chiamano, rilanciano o passano.\\nVincere la mano: il piatto si vince:\\n",
    "Four of a Kind: Four cards of the same rank (e.g., 9, 9, 9, 9).\\nFull House: Three cards of one rank and two of another (e.g., 3, 3, 3, 7, 7).\\nFlush: Five cards of the same suit in any order.\\nStraight: Five consecutive cards of mixed suits.\\nThree of a Kind: Three cards of the same rank.\\nTwo Pair: Two sets of two cards of the same rank (e.g., 5, 5, 8, 8).\\nOne Pair: Two cards of the same rank.\\nHigh Card: If no other hand is formed, the highest card wins (e.g., Ace beats King).": "Poker: quattro carte dello stesso valore (es. 9, 9, 9, 9).\\nFull: tre carte di un valore e due di un altro (es. 3, 3, 3, 7, 7).\\nColore: cinque carte dello stesso seme in qualsiasi ordine.\\nScala: cinque carte consecutive di semi diversi.\\nTris: tre carte dello stesso valore.\\nDoppia Coppia: due gruppi di due carte dello stesso valore (es. 5, 5, 8, 8).\\nCoppia: due carte dello stesso valore.\\nCarta Alta: se non si forma nessun'altra mano, vince la carta più alta (es. l'Asso batte il Re).",
    "Fold if you have a weak hand and the betting gets too high.\\nBluff wisely to make others fold, but don’t overdo it.\\nPay attention to other players' betting patterns to guess their hands.\\nEnjoy playing and good luck at the table!": "Passa se hai una mano debole e le puntate salgono troppo.\\nBlekka con criterio per far passare gli altri, ma non esagerare.\\nOsserva come puntano gli altri giocatori per intuire le loro mani.\\nDivertiti e buona fortuna al tavolo!",

    # ---- personaggio: razze, archetipi, personalita' ----------------------
    "Character Customization": "Personalizzazione del personaggio",
    "character name required": "nome del personaggio obbligatorio",
    "Quest Name Placeholder": "Segnaposto nome missione",
    "Your character's name.": "Il nome del tuo personaggio.",
    "Your character's race.": "La razza del tuo personaggio.",
    "Your character's class.": "La classe del tuo personaggio.",
    "Your character's archetype based on race and class.": "L'archetipo del tuo personaggio, in base a razza e classe.",
    "Your character's personality. Changes your dialogue responses.\\n": "La personalità del tuo personaggio. Cambia le tue risposte nei dialoghi.\\n",
    "Determines your characters attributes, scaling, and half your skill tree, alongside class": "Determina gli attributi del personaggio, la crescita e metà dell'albero delle abilità, insieme alla classe",
    "Determines your characters attributes, scaling, and half your skill tree, alongside class.": "Determina gli attributi del personaggio, la crescita e metà dell'albero delle abilità, insieme alla classe.",
    "A traditional hero, always acting with honor and chivalry.\\n": "Un eroe tradizionale, sempre mosso da onore e cavalleria.\\n",
    "Speaks with scholarly rhetoric, always interested to learn more.": "Parla con retorica erudita, sempre interessato a imparare di più.",
    "Makes a joke of any situation, carefree and relaxed even in the most dire circumstances.\\n": "Scherza su ogni situazione, spensierato e tranquillo anche nelle circostanze più disperate.\\n",
    "Dark, brooding, and unflinching, with emotions reserved and never showing weakness.\\n\\n": "Cupo, tormentato e imperturbabile, di emozioni riservate e mai disposto a mostrare debolezza.\\n\\n",
    "Increases Physical Power, increasing Strike, Thrust, and Blunt damage you deal. Grants access to more martial abilities.": "Aumenta il potere fisico, accrescendo il danno da taglio, perforante e contundente che infliggi. Dà accesso a più abilità marziali.",
    "Increases Physical Power, increasing Strike, Thrust, and Blunt damage you deal. Increases Attack Speed for faster basic combos. Grants access to more cunning abilities.": "Aumenta il potere fisico, accrescendo il danno da taglio, perforante e contundente che infliggi. Aumenta la velocità d'attacco per combo base più rapide. Dà accesso a più abilità astute.",
    "Increases Magic Power, increasing Fire, Ice, Electricity, Decay, and Ether damage you deal. Unlocks more destructive spells.": "Aumenta il potere magico, accrescendo il danno da fuoco, ghiaccio, elettricità, decadimento ed etere che infliggi. Sblocca incantesimi più distruttivi.",
    "Increases Magic Power, increasing Fire, Ice, Electricity, Decay, and Ether damage you deal. Grants access to more restorative and protective spells.": "Aumenta il potere magico, accrescendo il danno da fuoco, ghiaccio, elettricità, decadimento ed etere che infliggi. Dà accesso a più incantesimi curativi e protettivi.",
    "Renowned for their ingenuity and adaptability, humans are the most populous race in Mirkea. They thrive in diverse environments and contribute significantly to the realm's cultural and technological advancements.": "Celebri per ingegno e adattabilità, gli umani sono la razza più numerosa di Mirkea. Prosperano negli ambienti più diversi e contribuiscono molto al progresso culturale e tecnologico del regno.",
    "Minotaurs are towering, muscular beings with the head of a bull, known for their formidable strength, strategic thinking, and keen senses. Standing over 8 feet tall, they are respected and feared as fierce warriors and skilled tacticians across the Mirkea.": "I minotauri sono creature imponenti e muscolose con la testa di toro, note per forza formidabile, pensiero strategico e sensi acuti. Alti oltre due metri e mezzo, sono rispettati e temuti in tutta Mirkea come guerrieri feroci e tattici abili.",
    "Mirkea’s most populous and inventive folk who thrive anywhere. Adaptable all-rounders with balanced stats and the ability to switch between ranged and melee weapons, flexible for any role.": "Il popolo più numeroso e inventivo di Mirkea, capace di prosperare ovunque. Tuttofare adattabili, con statistiche equilibrate e la capacità di alternare armi da mischia e a distanza, flessibili per qualsiasi ruolo.",
    "Towering, bull-headed warriors of Mirkea with keen senses and tactical minds. Strength-focused frontline bruisers that attack with wide, sweeping axe strikes and soak damage": "Guerrieri imponenti dalla testa di toro di Mirkea, dai sensi acuti e dalla mente tattica. Picchiatori di prima linea votati alla forza, che attaccano con ampi fendenti d'ascia e assorbono i colpi",
    "Elemental spell caster commanding fire, ice, and lightning. Builds and detonates elemental combos to control crowds, exploit weaknesses, and unleash amplified burst damage at range.": "Incantatore elementale che comanda fuoco, ghiaccio e fulmine. Costruisce e fa detonare combo elementali per controllare le folle, sfruttare le debolezze e scatenare danno amplificato a distanza.",
    "Ferocious close-combat fighter mixing weapon blows with rapid, bone-rattling punches. Durable yet agile bruiser that staggers foes, maintains stamina-driven pressure, and dishes out burst melee damage.": "Combattente feroce nel corpo a corpo, che alterna colpi d'arma e pugni rapidi e devastanti. Picchiatore resistente ma agile, che sbilancia i nemici, mantiene una pressione basata sul vigore e scarica danno improvviso in mischia.",
    "A heavy battlemage who channels seismic power through sheer force and stonebound magic. Earthshakers crush clustered enemies, reshape terrain, and endure punishing blows without faltering.": "Un mago da battaglia pesante che canalizza potere sismico con forza bruta e magia legata alla pietra. Gli Scuotiterra schiacciano i nemici ammassati, rimodellano il terreno e resistono a colpi durissimi senza vacillare.",
    "A versatile spellcaster who commands fire and frost to adapt to any threat. Elemental Rangers excel at mid-range combat and tactical mobility, chaining elemental effects to control the battlefield.\\n": "Un incantatore versatile che comanda fuoco e gelo per adattarsi a ogni minaccia. I Ranger Elementali eccellono nel combattimento a media distanza e nella mobilità tattica, concatenando effetti elementali per controllare il campo di battaglia.\\n",
    "A stalwart frontline warrior who charges into battle, shattering lines and holding ground through sheer tenacity. Vanguards specialize in crowd control and disruption, using force and durability to dominate close quarters.": "Un guerriero saldo di prima linea che carica in battaglia, sfonda gli schieramenti e tiene la posizione per pura tenacia. Le Avanguardie sono specializzate nel controllo e nella disgregazione, usando forza e resistenza per dominare il corpo a corpo.",
    "Night’s Whispers are elusive assassins who cut, vanish, and cut again. They open from stealth to stack bleeding and poison, consume those wounds to gain Double Strike and Temporal Echo, and call shadow clones in to repeat every killing blow.": "I Sussurri della Notte sono assassini sfuggenti che colpiscono, svaniscono e colpiscono di nuovo. Aprono dalla furtività accumulando sanguinamento e veleno, consumano quelle ferite per ottenere Colpo doppio ed Eco temporale, e richiamano cloni d'ombra a ripetere ogni colpo mortale.",
    "Dreadhorns are brutal ambushers who bring the weight of an axe out of the dark. They open from stealth with rage-fuelled cleaves, convert bleeding into poison, and drive shadow shockwaves and plague tremors through the ground into everything around them.": "I Cornispavento sono brutali imboscatori che portano il peso di un'ascia fuori dal buio. Aprono dalla furtività con fendenti alimentati dalla furia, convertono il sanguinamento in veleno e propagano nel terreno onde d'ombra e tremori pestilenziali verso tutto ciò che li circonda.",
    "Gloom Stalkers are ambush hunters who fight from cover with poisoned bolts and a blade in the dark. They swap between crossbow and sword to slip into stealth, leave shadow clones behind to strike alongside them, and turn stacked poison into bursts of decay.": "I Cacciatori dell'Ombra sono predatori da imboscata che combattono al coperto con dardi avvelenati e una lama nel buio. Alternano balestra e spada per scivolare nella furtività, lasciano cloni d'ombra a colpire accanto a loro e trasformano il veleno accumulato in scariche di decadimento.",
    "Echo Weavers are duelling spellcasters who fold fire and frost into their blade work. They mark enemies with Temporal Echo, then set it off in bursts of flame and ice, turning one lingering affliction into another and making damage that has already landed happen twice.": "I Tessitori d'Eco sono incantatori duellanti che intrecciano fuoco e gelo al lavoro di lama. Marchiano i nemici con Eco temporale, poi la fanno detonare in scariche di fiamma e ghiaccio, trasformando un'afflizione persistente in un'altra e facendo accadere due volte un danno già inflitto.",
    "Phase Duellists are fast, close-range fighters who alternate dagger work and bare-fisted blows with bursts of temporal magic. They build Temporal Surge through relentless cuts and punches, then spend it to spread bleeding through a crowd, batter enemies into a stun, and step out of reach before the counterattack lands.": "I Duellanti di Fase sono combattenti rapidi a corto raggio che alternano il lavoro di pugnale e i colpi a mani nude a scariche di magia temporale. Accumulano Ondata temporale con tagli e pugni incessanti, poi la spendono per diffondere il sanguinamento nella folla, stordire i nemici a forza di colpi e sottrarsi alla portata prima che arrivi il contrattacco.",
    "A hunting hound native to Aldoria, commonly kept by village huntsmen.": "Un cane da caccia originario di Aldoria, tenuto comunemente dai cacciatori dei villaggi.",
    "A young Fangra wolf of the Wildwood Forest, not yet fully grown but already a vicious hunter.": "Un giovane lupo Fangra della Foresta di Wildwood, non ancora adulto ma già un cacciatore feroce.",
    "A breed born from ancient magical experimentation, Ember Hounds are now often treated as dangerous nuisances": "Una razza nata da antichi esperimenti magici, i Cani di Brace sono oggi spesso considerati un pericoloso fastidio",
    "Trained in Barrier magic at Aldoria’s Great Academy, Silver Cats are valued companions of mages sent into battle": "Addestrati nella magia di Barriera alla Grande Accademia di Aldoria, i Gatti Argentati sono compagni preziosi dei maghi mandati in battaglia",
    "Native to the frozen heights of the Dimraeth Mountains, Frost Owls hibernate in summer and roam Mirkea during winter": "Originarie delle alture ghiacciate dei Monti di Dimraeth, le Civette Gelide ibernano in estate e vagano per Mirkea durante l'inverno",
    "Native to the swamplands, Blight Crows seek out weakened prey, worsening their sickness as they stalk them for days.": "Originari delle paludi, i Corvi del Morbo cercano prede indebolite, aggravandone il male mentre le seguono per giorni.",
    "Predatory birds prized by hunters in Aldoria, Carrion Parrots excel at tracking the weak, the wounded, and the dying.": "Uccelli predatori apprezzati dai cacciatori di Aldoria, i Pappagalli Carogna eccellono nel seguire i deboli, i feriti e i moribondi.",
    "Native to the Barrenlands, War Cats are common companions of the Minotaurs of Xwin and often march beside them in battle.": "Originari delle Terre Sterili, i Gatti da Guerra sono compagni comuni dei minotauri di Xwin e marciano spesso al loro fianco in battaglia.",
    "A common companion of student mages in the Great Academy of Aldoria, known for its revitalising magic and calming presence.": "Compagno comune dei maghi studenti della Grande Accademia di Aldoria, noto per la sua magia rivitalizzante e la presenza rassicurante.",
    "High Priestess Althaea Of The Tirathlan": "Somma Sacerdotessa Althaea del Tirathlan",
    "Adventurers B1 - Corin's Followers": "Avventurieri B1 - Seguaci di Corin",
    "Adventurers from the random event \"Corin's Followers 1\" version B.": "Avventurieri dall'evento casuale \"Seguaci di Corin 1\" versione B.",
    "Dryad Rootweaver Corrupted Beast Key": "Chiave della bestia corrotta: Driade Tessiradici",
    "Dryad Beastwarden Corrupted Beast Key": "Chiave della bestia corrotta: Driade Custode delle Bestie",
    "Dryad Rivercaller Corrupted Beast Key": "Chiave della bestia corrotta: Driade Rivercaller",

    # ---- refusi e segnaposto del sorgente ---------------------------------
    "Thanks for Playing!\\n\\n\\nYou defeated the Corrupted Treant and completed the main story available in the Dimraeth Demo.\\n\\n\\nYou can keep playing to find more side quests, strengthen your character, and replay Deeds.\\n\\n\\nIf you enjoyed the game, please consider leaving a review. It helps us improve Dimraeth and reach more players.": "Grazie per aver giocato!\\n\\n\\nHai sconfitto il Treant corrotto e completato la storia principale disponibile nella demo di Dimraeth.\\n\\n\\nPuoi continuare a giocare per trovare altre missioni secondarie, potenziare il personaggio e rigiocare gli incarichi.\\n\\n\\nSe il gioco ti è piaciuto, considera di lasciare una recensione. Ci aiuta a migliorare Dimraeth e a raggiungere più giocatori.",
    # questa riga era rimasta in portoghese nel CSV inglese
    "Obrigado por Jogar!\\n\\nVocê derrotou o Treant Corrompido e completou a história principal disponível na Demo de Dimraeth.\\n\\nVocê pode continuar jogando para encontrar mais missões secundárias, fortalecer seu personagem e refazer Feitos.\\n\\nSe você gostou do jogo, considere deixar uma avaliação. Isso nos ajuda a melhorar Dimraeth e alcançar mais jogadores.": "Grazie per aver giocato!\\n\\nHai sconfitto il Treant corrotto e completato la storia principale disponibile nella demo di Dimraeth.\\n\\nPuoi continuare a giocare per trovare altre missioni secondarie, potenziare il personaggio e rigiocare gli incarichi.\\n\\nSe il gioco ti è piaciuto, considera di lasciare una recensione. Ci aiuta a migliorare Dimraeth e a raggiungere più giocatori.",
    "Deed Name Deed Name Deed NameDeed NameDeed Name": "Nome Incarico Nome Incarico Nome IncaricoNome IncaricoNome Incarico",
    "Blightseed, Pathweaver, Ironfist, Momentum, Blablabla, acsncdnfn,duhfsjsjfkll": "Blightseed, Pathweaver, Ironfist, Momentum, Blablabla, acsncdnfn,duhfsjsjfkll",

    # ---- code lunghe emerse dal controllo di copertura ---------------------
    "{0} has killed {1} with {2}": "{0} ha ucciso {1} con {2}",
    "SUB-ENTRIES": "SOTTOVOCI",
    "Minotaur": "Minotauro",
    "Controller Type": "Tipo di controller",
    "Deed level: 12": "Livello dell'incarico: 12",
    # 'Table' fuori dal contesto poker: e' il tavolo come mobile o schermata
    "Table": "Tavolo",
    "+{0}% XP, -{1}% decay": "+{0}% XP, -{1}% decadimento",
}
