# -*- coding: utf-8 -*-
"""Traduzioni del lotto UI-chrome, indicizzate per testo inglese.

433 testi distinti coprono 576 chiavi: molte chiavi condividono la stessa stringa
(UI_..._ACTION compare 75 volte), quindi conviene tradurre il testo, non la chiave.

Note lasciate nel codice dove la scelta non e' ovvia. Le stringhe di prova del
layout ('The Longest Name', 'Thelongestnamee') e le voci di debug ('God Mode Deer',
'Training Dummy') sono tradotte comunque: non fanno danno e restano riconoscibili.
"""

T = {
    # ---- aree -------------------------------------------------------------
    "Earlwood Farmlands": "Terre coltivate di Earlwood",
    "Earlwood Forest East": "Foresta di Earlwood Est",
    "Earlwood Village": "Villaggio di Earlwood",
    "The Guild Hall": "La Sede della Gilda",
    "The Sanctum": "Il Santuario",
    "Qallaw's House": "Casa di Qallaw",
    "Shazhn's House": "Casa di Shazhn",
    "The Forest Throne": "Il Trono della Foresta",
    "Goblin Caves": "Caverne dei Goblin",
    "The Lost Caverns": "Le Caverne Perdute",
    "Corrupted Thicket": "Boscaglia corrotta",
    "Wildwood Forest": "Foresta di Wildwood",
    "Farmlands East": "Terre coltivate Est",
    "Farmlands Road": "Strada delle terre coltivate",
    "Farmlands West": "Terre coltivate Ovest",
    "Grimhollow Pines": "Pini di Grimhollow",
    "Lost Caverns East": "Caverne Perdute Est",
    "Lost Caverns West": "Caverne Perdute Ovest",
    "Sanctum Alpha": "Santuario Alpha",
    "Southbarrows": "Southbarrows",
    "The Corrupted Glade": "La Radura Corrotta",
    "The Rootcall Veil": "Il Velo del Richiamo delle Radici",
    "The Rootward Road": "La Strada delle Radici",

    # ---- messaggi e notifiche ---------------------------------------------
    "You are blocked by that player": "Quel giocatore ti ha bloccato",
    "The bells of Dimraeth toll for {0}": "Le campane di Dimraeth suonano per {0}",
    "A {0} has killed {1}": "Un {0} ha ucciso {1}",
    "A {0} has killed {1} with {2}": "Un {0} ha ucciso {1} con {2}",
    "[Server]": "[Server]",
    "Aid the adventurers.": "Aiuta gli avventurieri.",
    "Corin's Followers": "Seguaci di Corin",
    "level {0}": "livello {0}",
    "(MAX)": "(MAX)",
    "New Build Unlocked: {0}": "Nuova costruzione sbloccata: {0}",
    "Crops ready for harvest": "Colture pronte per il raccolto",
    "Skill Points Unlocked: {0}": "Punti abilità sbloccati: {0}",
    "New Skill Point Unlocked": "Nuovo punto abilità sbloccato",
    "You are already in a party": "Sei già in un gruppo",
    "Party {0} created": "Gruppo {0} creato",
    "Party has been disbanded": "Il gruppo è stato sciolto",
    "Party Disbanded": "Gruppo sciolto",
    "Party invite from: {0}": "Invito al gruppo da: {0}",
    "Invite sent to: {0}": "Invito inviato a: {0}",
    "You have left the party": "Hai lasciato il gruppo",
    "New Member Joined the Sanctum": "Un nuovo membro si è unito al Santuario",
    "New pet available at Myrll's Shop": "Nuovo compagno disponibile al Negozio di Myrll",
    "Formidable Foe Slain": "Nemico formidabile ucciso",
    "Legendary Foe Slain": "Nemico leggendario ucciso",
    "You leveled up!": "Sei salito di livello!",
    "Point of Interest Found:": "Punto d'interesse trovato:",
    "No news at this time": "Nessuna novità al momento",
    "Unable to load news": "Impossibile caricare le novità",
    "Experience points earned.": "Punti esperienza guadagnati.",
    "Click again to abandon: {0}": "Clicca di nuovo per abbandonare: {0}",
    "Attributes respec'd!": "Attributi riassegnati!",
    "Spell Already Unlocked": "Incantesimo già sbloccato",
    "Spectating: {0}": "Stai osservando: {0}",

    # ---- risorse ----------------------------------------------------------
    "Apple": "Mela",
    "Carrot": "Carota",
    "Coal": "Carbone",
    "Copper": "Rame",
    "Donation": "Donazione",
    "Emberbloom": "Emberbloom",
    "Gemini": "Gemini",
    "Heart Oak Log": "Tronco di Quercia del Cuore",
    "Iron": "Ferro",
    "Large Rock A": "Roccia grande A",
    "Large Rock B": "Roccia grande B",
    "Log A": "Tronco A",
    "Log B": "Tronco B",
    "Log C": "Tronco C",
    "Loose Stone": "Pietra smossa",
    "Pinewood Branch": "Ramo di pino",
    "Pinewood Log": "Tronco di pino",
    "Potato": "Patata",
    "Salt": "Sale",
    "Singing Bellflower": "Campanula Canterina",
    "Small Rock": "Roccia piccola",
    "Tenderberry": "Tenderberry",
    "Thaumablossom": "Thaumablossom",
    "Woodland Flax": "Lino silvestre",
    "Flowers and Acorns": "Fiori e ghiande",
    "Pinewood [1/13]": "Pino [1/13]",

    # ---- consumabili e categorie -----------------------------------------
    "Bandage": "Benda",
    "Boon Potion": "Pozione del Favore",
    "Burn Salve": "Unguento per ustioni",
    "Concentration Potion": "Pozione di concentrazione",
    "Health Potion": "Pozione di salute",
    "Offensive Tool": "Strumento offensivo",
    "Poison Cure": "Antidoto",
    "Stamina Potion": "Pozione di vigore",
    "Weapon Oil": "Olio per armi",
    "Cure": "Cura",
    "Drink": "Bevanda",
    "Food": "Cibo",
    "Harvest Tool": "Strumento di raccolta",
    "Weapon": "Arma",
    "Potion": "Pozione",
    "Resource": "Risorsa",
    "Spellbook": "Libro degli incantesimi",
    "Alcohol": "Alcolici",

    # ---- creature ---------------------------------------------------------
    # I nomi inventati e opachi restano (Droop, Drooplet, Flaskrat, Smashmouth):
    # tradurli produrrebbe invenzioni arbitrarie. Gli epiteti trasparenti
    # (Basher, Ripper, Spitter, Empowered) si traducono.
    "Aelwynor The Wildroot Father": "Aelwynor il Padre delle Radici Selvatiche",
    "Aelwynor The Wildroot Father Deed": "Incarico: Aelwynor il Padre delle Radici Selvatiche",
    "Bandit": "Bandito",
    "Basilisk": "Basilisco",
    "Briarheart The Firecursed": "Briarheart il Maledetto dal Fuoco",
    "Chick": "Pulcino",
    "Chicken": "Gallina",
    "Corrupted Droop": "Droop corrotto",
    "Corrupted Droop Empowered": "Droop corrotto potenziato",
    "Corrupted Forest King": "Re della Foresta corrotto",
    "Corrupted Heart": "Cuore corrotto",
    "Corrupted Heart False Lead": "Cuore corrotto (falsa pista)",
    "Corrupted Monstrous Droop": "Droop mostruoso corrotto",
    "Corrupted Treant": "Treant corrotto",
    "Corrupted Wildwood Wolf": "Lupo di Wildwood corrotto",
    "Corrupted Wildwood Wolf Empowered": "Lupo di Wildwood corrotto potenziato",
    "Deer": "Cervo",
    "Droop Empowered": "Droop potenziato",
    "Drooplet": "Drooplet",
    "Drooplet Empowered": "Drooplet potenziato",
    "Droop Nest": "Nido di Droop",
    "Droop Spitter": "Droop sputatore",
    "Droop Spitter Empowered": "Droop sputatore potenziato",
    "Dryad": "Driade",
    "Dryad Beastwarden": "Driade Custode delle Bestie",
    "Dryad Beastwarden Empowered": "Driade Custode delle Bestie potenziata",
    "Dryad Rivercaller": "Driade Rivercaller",
    "Dryad Rivercaller Empowered": "Driade Rivercaller potenziata",
    "Dryad Rootweaver": "Driade Tessiradici",
    "Dryad Rootweaver Empowered": "Driade Tessiradici potenziata",
    "Forest Heart": "Cuore della Foresta",
    "Gargoyle": "Gargoyle",
    "Goblin Basher": "Goblin Picchiatore",
    "Goblin Basher Empowered": "Goblin Picchiatore potenziato",
    "Goblin Basher T2": "Goblin Picchiatore T2",
    "Goblin Devour Runner": "Goblin Corridore Divoratore",
    "Goblin Flaskrat": "Goblin Flaskrat",
    "Goblin Flaskrat Empowered": "Goblin Flaskrat potenziato",
    "Goblin Flaskrat T2": "Goblin Flaskrat T2",
    "Goblin Flaskrat T2Empowered": "Goblin Flaskrat T2 potenziato",
    "Goblin King": "Re Goblin",
    "Goblin Ripper": "Goblin Squartatore",
    "Goblin Ripper Empowered": "Goblin Squartatore potenziato",
    "Goblin Ripper T2": "Goblin Squartatore T2",
    "Goblin Ripper T2Empowered": "Goblin Squartatore T2 potenziato",
    "God Mode Deer": "Cervo God Mode",
    "Gorilla": "Gorilla",
    "Gotburg The Burned": "Gotburg l'Ustionato",
    "Harpy": "Arpia",
    "JJ Fish": "Pesce JJ",
    "Monstrous Droop": "Droop mostruoso",
    "Monstrous Droop Farmlands": "Droop mostruoso delle terre coltivate",
    "Pale Bark The Old Oak": "Pale Bark la Vecchia Quercia",
    "Rabbit": "Coniglio",
    "Rageborn Flaskrat": "Flaskrat nato dalla furia",
    "Rageborn Ripper": "Squartatore nato dalla furia",
    "Rotting Treant": "Treant putrescente",
    "Rotting Treant Empowered": "Treant putrescente potenziato",
    "Sleeping Droop": "Droop dormiente",
    "Smashmouth": "Smashmouth",
    "Snake": "Serpente",
    "Spider": "Ragno",
    "Squirrel": "Scoiattolo",
    "Training Dummy": "Manichino da allenamento",
    "Treant": "Treant",
    "Treant Empowered": "Treant potenziato",
    "Wildwood Aetherfang Wolf": "Lupo Zanna d'Etere di Wildwood",
    "Wildwood Aetherfang Wolf Empowered": "Lupo Zanna d'Etere di Wildwood potenziato",
    "Wildwood Wolf": "Lupo di Wildwood",
    "Wildwood Wolf Alpha": "Lupo di Wildwood alfa",
    "Wildwood Wolf Alpha B": "Lupo di Wildwood alfa B",
    "Wildwood Wolf Empowered": "Lupo di Wildwood potenziato",
    "Woldroot The Path Guardian": "Woldroot il Guardiano del Sentiero",

    # ---- compagni ---------------------------------------------------------
    "Blight Crow": "Corvo del Morbo",
    "Carrion Parrot": "Pappagallo Carogna",
    "Ember Hound": "Cane di Brace",
    "Fangra Cub": "Cucciolo di Fangra",
    "Frost Owl": "Civetta Gelida",
    "Hound": "Cane",
    "Monkey": "Scimmia",
    "Moon Cat": "Gatto Lunare",
    "Silver Cat": "Gatto Argentato",
    "War Cat": "Gatto da Guerra",

    # ---- livelli di relazione --------------------------------------------
    "Destined Paramour": "Amante Predestinato",
    "Emerging Friend": "Amicizia Nascente",
    "Fated Paramour": "Amante del Destino",
    "Fervent Lover": "Amante Fervente",
    "Ideological Paragon": "Modello Ideologico",
    "Ideological Spark": "Scintilla Ideologica",
    "Kindred Companion": "Compagno Affine",
    "Kindred Soul": "Anima Affine",
    "Loyal Companion": "Compagno Leale",
    "Passionate Partner": "Partner Appassionato",
    "Romantic Companion": "Compagno Romantico",
    "Romantic Interest": "Interesse Romantico",
    "Soul Mate": "Anima Gemella",
    "Steadfast Ally": "Alleato Fedele",
    "Steady Companion": "Compagno Stabile",
    "Stranger": "Sconosciuto",

    # ---- negozi -----------------------------------------------------------
    "Basilton's Seeds": "Sementi di Basilton",
    "Befr's Shop": "Negozio di Befr",
    "Corin's Shop": "Negozio di Corin",
    "Daw's Shop": "Negozio di Daw",
    "Diyar's Pet Shop": "Negozio di compagni di Diyar",
    "Dzn's Shop": "Negozio di Dzn",
    "Manga's Equipment": "Equipaggiamento di Manga",
    "Saqi's Tavern": "Taverna di Saqi",
    "Scavenger Guard Shop": "Negozio della Guardia Saccheggiatrice",
    "Shazhn's Shop": "Negozio di Shazhn",
    "Suspicious Shop": "Negozio sospetto",
    "Tamsin's Shop": "Negozio di Tamsin",
    "Traveling Merchant": "Mercante ambulante",

    # ---- slot di equipaggiamento -----------------------------------------
    "Amulet": "Amuleto",
    "Badge": "Distintivo",
    "Belt": "Cintura",
    "Bracer": "Bracciale",
    "Charm": "Ciondolo",
    "Ring": "Anello",
    "Rune": "Runa",
    "Under-coat": "Sottoveste",

    # ---- statistiche ------------------------------------------------------
    # 'Piercing' -> 'Penetrazione' per non collidere con 'perforante' (tipo Thrust).
    "Armor": "Armatura",
    "Armor Percent": "Armatura %",
    "Armor Penetration": "Penetrazione dell'armatura",
    "Armor Penetration Percent": "Penetrazione dell'armatura %",
    "Attack Damage": "Danno d'attacco",
    "Attack Speed": "Velocità d'attacco",
    "Bleeding Damage": "Danno da sanguinamento",
    "Bleeding Duration": "Durata sanguinamento",
    "Blunt Armor": "Armatura contundente",
    "Blunt Damage": "Danno contundente",
    "Blunt Piercing": "Penetrazione contundente",
    "Burning Damage": "Danno da ustione",
    "Burning Duration": "Durata ustione",
    "Chill Duration": "Durata gelo",
    "Chill Power": "Potenza del gelo",
    "Concentration On Hit": "Concentrazione al colpo",
    "Concentration Percent": "Concentrazione %",
    "Concentration Regen": "Rigen. concentrazione",
    "Critical Chance": "Probabilità di critico",
    "Critical Chance vs. Bleeding": "Probabilità di critico vs. sanguinamento",
    "Critical Chance vs. Burning": "Probabilità di critico vs. ustione",
    "Critical Chance vs. Chilled": "Probabilità di critico vs. assiderato",
    "Critical Chance vs. Poisoned": "Probabilità di critico vs. avvelenato",
    "Critical Chance vs. Stunned": "Probabilità di critico vs. stordito",
    "Critical Damage": "Danno critico",
    "Critical Damage vs. Bleeding": "Danno critico vs. sanguinamento",
    "Critical Damage vs. Burning": "Danno critico vs. ustione",
    "Critical Damage vs. Chilled": "Danno critico vs. assiderato",
    "Critical Damage vs. Poisoned": "Danno critico vs. avvelenato",
    "Critical Damage vs. Stunned": "Danno critico vs. stordito",
    "Damage vs. Bleeding": "Danno vs. sanguinamento",
    "Damage vs. Burning": "Danno vs. ustione",
    "Damage vs. Chilled": "Danno vs. assiderato",
    "Damage vs. Full Health": "Danno vs. salute massima",
    "Damage vs. <40% HP": "Danno vs. <40% HP",
    "Damage vs. Poisoned": "Danno vs. avvelenato",
    "Damage vs. Stunned": "Danno vs. stordito",
    "Decay Damage": "Danno da decadimento",
    "Decay Piercing": "Penetrazione da decadimento",
    "Decay Resistance": "Resistenza al decadimento",
    "Electricity Damage": "Danno da elettricità",
    "Electricity Piercing": "Penetrazione da elettricità",
    "Electricity Resistance": "Resistenza all'elettricità",
    "Ether Damage": "Danno da etere",
    "Ether Piercing": "Penetrazione da etere",
    "Ether Resistance": "Resistenza all'etere",
    "Fire Damage": "Danno da fuoco",
    "Fire Piercing": "Penetrazione da fuoco",
    "Fire Resistance": "Resistenza al fuoco",
    "Guard Efficiency": "Efficienza della guardia",
    "Health Regen": "Rigen. salute",
    "HP Percent": "HP %",
    "Ice Damage": "Danno da ghiaccio",
    "Ice Piercing": "Penetrazione da ghiaccio",
    "Ice Resistance": "Resistenza al ghiaccio",
    "Magic Damage": "Danno magico",
    "Magic Damage Percent": "Danno magico %",
    "Magic Piercing": "Penetrazione magica",
    "Magic Power": "Potere magico",
    "Max Bleeding": "Sanguinamento max",
    "Max Burning": "Ustione max",
    "Max Chill": "Gelo max",
    "Max Poison": "Veleno max",
    "Max Rage": "Furia max",
    "Max Shock": "Scossa max",
    "Increases your Movement Speed.": "Aumenta la tua velocità di movimento.",
    "Movement Speed": "Velocità di movimento",
    "Next Level XP": "XP prossimo livello",
    "Physical Damage": "Danno fisico",
    "Physical Damage Percent": "Danno fisico %",
    "Physical Piercing": "Penetrazione fisica",
    "Physical Power": "Potere fisico",
    "Poison Damage": "Danno da veleno",
    "Poison Duration": "Durata veleno",
    "Poison Piercing": "Penetrazione da veleno",
    "Rage Duration": "Durata furia",
    "Resistance": "Resistenza",
    "Resistance Penetration": "Penetrazione delle resistenze",
    "Resistance Penetration Percent": "Penetrazione delle resistenze %",
    "Resistance Percent": "Resistenza %",
    "Speed": "Velocità",
    "Spell Haste": "Celerità magica",
    "Stamina Percent": "Vigore %",
    "Stamina Regen": "Rigen. vigore",
    "Strike Armor": "Armatura da taglio",
    "Strike Damage": "Danno da taglio",
    "Strike Piercing": "Penetrazione da taglio",
    "Stun Build-up": "Accumulo di stordimento",
    "Thrust Armor": "Armatura perforante",
    "Thrust Damage": "Danno perforante",
    "Thrust Piercing": "Penetrazione perforante",
    "Mana": "Mana",

    # ---- archetipi e abilità ---------------------------------------------
    "Earthshaker": "Scuotiterra",
    "Elemental Ranger": "Ranger Elementale",
    "Vanguard": "Avanguardia",
    "Wildstrider": "Passosilvestre",
    "Multistrike": "Colpo multiplo",
    "Cornu Charge": "Carica di Cornu",
    "Pulverize": "Polverizza",
    "Quick Jab": "Jab rapido",
    "Seismic Stampede": "Carica sismica",
    "Weapon Swap": "Cambio arma",

    # ---- comandi e pulsanti ----------------------------------------------
    "Action": "Azione",
    "Back": "Indietro",
    "Cancel": "Annulla",
    "Choose": "Scegli",
    "Close": "Chiudi",
    "Confirm": "Conferma",
    "Delete": "Elimina",
    "Exit": "Esci",
    "Join": "Unisciti",
    "Leave": "Esci",
    "Navigate": "Naviga",
    "Reorder": "Riordina",
    "Scroll": "Scorri",
    "Search": "Cerca",
    "Travel": "Viaggia",
    "Talk": "Parla",
    "Buy": "Compra",
    "Buy Back": "Riacquista",
    "Sell": "Vendi",
    "Craft": "Crea",
    "Drop": "Getta",
    "Dismantle": "Smonta",
    "Abandon": "Abbandona",
    "Disband": "Sciogli",
    "Hold": "Tieni premuto",
    "Button": "Pulsante",
    "Tab": "Tab",
    "Queue": "Coda",
    "Move Up": "Sposta su",
    "Next Page": "Pagina successiva",
    "Next Color": "Colore successivo",
    "Previous Color": "Colore precedente",
    "Send To": "Invia a",
    "Send to Pet": "Invia al compagno",
    "Choose pet": "Scegli compagno",
    "Continue Game": "Continua partita",
    # nel CSV inglese questa voce e' rimasta in portoghese: refuso nel sorgente
    "Continuar Jogo": "Continua partita",
    "Enter text...": "Inserisci testo...",
    "hold to craft": "tieni premuto per creare",
    "Hold to Sprint": "Tieni premuto per scattare",
    "Hold to Reset Bindings": "Tieni premuto per azzerare i comandi",
    "Click this button to track quest": "Clicca questo pulsante per seguire la missione",
    "Select to 'Fast Travel'": "Seleziona per il viaggio rapido",
    "Open Profile Window": "Apri finestra del profilo",
    "Track Quest": "Segui missione",
    "Track Name": "Nome traccia",
    "Place Beacon": "Piazza segnalatore",
    "Delete Beacon": "Elimina segnalatore",
    "Show on Map": "Mostra sulla mappa",
    "Show tooltip": "Mostra descrizione",
    "Toggle Tooltips": "Mostra/nascondi descrizioni",
    "Respec All": "Riassegna tutto",
    "Respec All: 20 points": "Riassegna tutto: 20 punti",
    "Change Party Name": "Cambia nome del gruppo",
    "Manage Bans": "Gestisci i bandi",

    # ---- schermate e voci di interfaccia ---------------------------------
    "Map": "Mappa",
    "Inventory": "Inventario",
    "Skills": "Abilità",
    "Skill Tree": "Albero delle abilità",
    "Spells": "Incantesimi",
    "Quests": "Missioni",
    "Waypoints": "Punti di passaggio",
    "Waygates": "Varchi",
    "Filters": "Filtri",
    "Social": "Sociale",
    "Location": "Posizione",
    "Owner": "Proprietario",
    "Price": "Prezzo",
    "Quantity": "Quantità",
    "Total": "Totale",
    "Gold": "Oro",
    "Hours": "Ore",
    "Hunger": "Fame",
    "Thirst": "Sete",
    "Nourishment": "Nutrimento",
    "Hair": "Capelli",
    "Female": "Femmina",
    "Male": "Maschio",
    "Everyone": "Tutti",
    "Moderate": "Moderato",
    "Learned": "Appreso",
    "Description:": "Descrizione:",
    "Cooking Skill:": "Abilità cucina:",
    "Party Name": "Nome del gruppo",
    "Followers [{0}/{1}]": "Seguaci [{0}/{1}]",
    "Available Points": "Punti disponibili",
    "Spent Points": "Punti spesi",
    "free point": "punto gratuito",
    "Attributes Required": "Attributi richiesti",
    "Require Attribute": "Attributo richiesto",
    "Exclusive with": "Esclusivo con",
    "Casting Selection": "Selezione del lancio",
    "No matches": "Nessun risultato",
    "N/A": "N/D",
    "LVL": "LIV",
    "Lvl": "Liv",
    "{0} - {1}-Piece: {2}": "{0} - {1} pezzi: {2}",
    "{0} - Set active": "{0} - Set attivo",
    "Move: Press ": "Movimento: premi ",
    "I have done that": "L'ho fatto",
    "I have not done that": "Non l'ho fatto",

    # ---- impostazioni -----------------------------------------------------
    "Full Screen": "Schermo intero",
    "Master Volume": "Volume principale",
    "Screen Shake": "Scuotimento dello schermo",
    "Multiplayer Settings": "Impostazioni multigiocatore",
    "Hide Player Names": "Nascondi i nomi dei giocatori",
    "Auto-Open Doors": "Apertura automatica delle porte",
    "Controller": "Controller",
    "Mouse": "Mouse",

    # ---- stringhe di prova del layout ------------------------------------
    "The Longest Name": "Il Nome Più Lungo",
    "Thelongestnamee": "Thelongestnamee",
}
