# -*- coding: utf-8 -*-
"""Etichette brevi della UI (secondo lotto).

Due dizionari, applicati in quest'ordine:

  OVERRIDES  indicizzato per CHIAVE del CSV. Serve quando la stessa stringa
             inglese vale due cose diverse: 'Straight' e' "Diretto" nel pugilato
             (nome di attacco) ma "Scala" nel poker. Senza override uno dei due
             contesti sarebbe sbagliato per forza.
  L          indicizzato per TESTO inglese, come il lotto precedente.

Le sequenze \\n nei valori sono due caratteri veri (barra + n) che TextMeshPro
rende come interruzione di riga: vanno preservate identiche.
"""

# Stringhe il cui significato dipende dalla schermata: vincono sul dizionario per testo.
OVERRIDES_BY_GROUP = {
    # gruppo UI_<X>_ -> {testo inglese: italiano}
    "POKER": {
        "Straight": "Scala",
        "Flush": "Colore",
        "Straight Flush": "Scala Reale",
        "Royal Flush": "Scala Reale Massima",
        "Four of a Kind": "Poker",
        "Full House": "Full",
        "Three of a Kind": "Tris",
        "Two Pair": "Doppia Coppia",
        "Pair": "Coppia",
        "High Card": "Carta Alta",
        "Check": "Passo",
        "Split": "Divisione",
        "Set": "Puntata",
        "Table": "Tavolo",
    },
}

L = {
    # ---- risposte e comandi di base ---------------------------------------
    "Yes": "Sì",
    "No": "No",
    "Accept": "Accetta",
    "ACCEPT": "ACCETTA",
    "Apply": "Applica",
    "Continue": "Continua",
    "Cancel/Back": "Annulla/Indietro",
    "Cancel Queue": "Annulla la coda",
    "Next": "Avanti",
    "Next page": "Pagina successiva",
    "Next Tab": "Scheda successiva",
    "Previous Tab": "Scheda precedente",
    "Next/Previous": "Successivo/Precedente",
    "Switch page": "Cambia pagina",
    "Start": "Inizia",
    "Quit": "Esci",
    "Open": "Apri",
    "Use": "Usa",
    "Use/Equip": "Usa/Equipaggia",
    "Equip": "Equipaggia",
    "Equipped": "Equipaggiato",
    "Inspect": "Esamina",
    "Interact": "Interagisci",
    "Move": "Muovi",
    "Move Up": "Sposta su",
    "Move Down": "Sposta giù",
    "Move Left": "Sposta a sinistra",
    "Move Right": "Sposta a destra",
    "Rotate": "Ruota",
    "Reset": "Azzera",
    "Refresh": "Aggiorna",
    "Rename": "Rinomina",
    "Copy": "Copia",
    "Sort": "Ordina",
    "Sort & Filter": "Ordina e filtra",
    "Sort by:": "Ordina per:",
    "Order by": "Ordina per",
    "Order:": "Ordine:",
    "Ascending": "Crescente",
    "Descending": "Decrescente",
    "Filter": "Filtro",
    "Filter Menu": "Menu dei filtri",
    "Filter:": "Filtro:",
    "Show Filters": "Mostra i filtri",
    "Hide Filters": "Nascondi i filtri",
    "Show Only": "Mostra solo",
    "Select": "Seleziona",
    "Reroll": "Ritira",
    "Split": "Dividi",
    "Salvage": "Recupera",
    "Salvage All": "Recupera tutto",
    "Salvage all": "Recupera tutto",
    "Deliver": "Consegna",
    "Donate": "Dona",
    "Contribute": "Contribuisci",
    "Contribute All": "Contribuisci con tutto",
    "Trade": "Scambia",
    "Train": "Allena",
    "Rest": "Riposa",
    "Sleep": "Dormi",
    "Sit In": "Entra al tavolo",
    "Sit Out": "Salta il turno",
    "Teleport": "Teletrasporto",
    "Teleport To:": "Teletrasporto a:",
    "Recall Pet": "Richiama il compagno",
    "Hunt": "Caccia",
    "Cull": "Abbatti",
    "Upgrade": "Migliora",
    "Upgrade Cost": "Costo del miglioramento",
    "Respec": "Riassegna",
    "Respec All:": "Riassegna tutto:",
    "Respec Cost:": "Costo di riassegnazione:",
    "Reset Attributes": "Azzera gli attributi",
    "Hide": "Nascondi",
    "Don't show": "Non mostrare",
    "Press": "Premi",
    "Press '{0}'": "Premi '{0}'",
    "Press to build": "Premi per costruire",
    "Hold to build": "Tieni premuto per costruire",
    "...or hold": "...o tieni premuto",
    "to cancel": "per annullare",
    "to revive": "per rianimare",
    "Pause/Play": "Pausa/Riproduci",
    "Play/Pause": "Riproduci/Pausa",
    "Speed Up": "Accelera",
    "Take All": "Prendi tutto",
    "Take all": "Prendi tutto",
    "Take Matching": "Prendi i corrispondenti",
    "Deposit All": "Deposita tutto",
    "Deposit Matching": "Deposita i corrispondenti",
    "Send All": "Invia tutto",
    "Send Half": "Invia metà",
    "Send Item": "Invia oggetto",
    "Send Stack": "Invia la pila",
    "Send Matching": "Invia i corrispondenti",
    "Transfer Item": "Trasferisci oggetto",
    "Transfer item": "Trasferisci oggetto",
    "Transfer Stack": "Trasferisci la pila",
    "Transfer all items": "Trasferisci tutti gli oggetti",
    "Move Item": "Sposta oggetto",
    "Move item": "Sposta oggetto",
    "Drop Item": "Getta oggetto",
    "Drop Stack": "Getta la pila",
    "Sell Item": "Vendi oggetto",
    "Sell Half": "Vendi metà",
    "Sell Stack": "Vendi la pila",
    "Quick Buy": "Acquisto rapido",
    "Quick Sell": "Vendita rapida",
    "Quick Cast": "Lancio rapido",
    "Buy Multiple": "Compra più unità",
    "Buy Stack": "Compra la pila",
    "Buy-Back": "Riacquista",
    "Create": "Crea",
    "Create New Character": "Crea nuovo personaggio",
    "Create New World": "Crea nuovo mondo",
    "Edit Name": "Modifica nome",
    "Edit Player Limit": "Modifica limite giocatori",
    "Name Confirm": "Conferma nome",
    "Confirm Targeting": "Conferma bersaglio",
    "Disable Auto Target": "Disattiva mira automatica",
    "Leave Party": "Lascia il gruppo",
    "Leave Conversation": "Termina la conversazione",
    "Change World": "Cambia mondo",
    "Join World": "Entra nel mondo",
    "Open Trade Window": "Apri la finestra di scambio",
    "Share Map Fragments": "Condividi i frammenti di mappa",
    "Complete Map": "Mappa completa",
    "Complete Task Group": "Completa il gruppo di compiti",
    "Unlock Builds": "Sblocca le costruzioni",
    "Cycle Tooltip": "Scorri la descrizione",
    "Increase/Decrease": "Aumenta/Diminuisci",
    "Navigate Options": "Scorri le opzioni",
    "Menu Navigation": "Navigazione del menu",
    "In-Game Navigation": "Navigazione in gioco",
    "Show on map": "Mostra sulla mappa",

    # ---- attributi e statistiche ------------------------------------------
    "Strength": "Forza",
    "Strength:": "Forza:",
    "Str": "For",
    "Agility": "Agilità",
    "Agility:": "Agilità:",
    "Intelligence": "Intelligenza",
    "Intelligence:": "Intelligenza:",
    "Charisma": "Carisma",
    "Charisma:": "Carisma:",
    "Physique": "Costituzione",
    "Physique:": "Costituzione:",
    "Energy": "Energia",
    "Energy:": "Energia:",
    "Attribute": "Attributo",
    "Attributes": "Attributi",
    "Attribute Stats": "Valori degli attributi",
    "Total Attributes": "Attributi totali",
    "Archetype Attributes": "Attributi dell'archetipo",
    "Required Attribute:": "Attributo richiesto:",
    "Basic Stats": "Statistiche di base",
    "Core Stats": "Statistiche principali",
    "Core stats": "Statistiche principali",
    "Statistics": "Statistiche",
    "New Stat": "Nuova statistica",
    "Health": "Salute",
    "Health:": "Salute:",
    "HP Percent:": "HP %:",
    "Stamina": "Vigore",
    "Stamina:": "Vigore:",
    "Stamina Percent:": "Vigore %:",
    "Stamina Regeneration": "Rigenerazione del vigore",
    "Concentration": "Concentrazione",
    "Concentration:": "Concentrazione:",
    "Lesser Concent": "Concentr. minore",
    "Regen": "Rigen.",
    "Encumbrance": "Ingombro",
    "Encumbrance:": "Ingombro:",
    "Encumbrance Bonus": "Bonus ingombro",
    "Icon of Encumbrance": "Icona dell'ingombro",
    "Weight": "Peso",
    "Capacity": "Capienza",
    "Durability": "Durabilità",
    "Percent": "Percentuale",
    "Damage": "Danno",
    "Attack": "Attacco",
    "Attack Damage:": "Danno d'attacco:",
    "Attack Speed:": "Velocità d'attacco:",
    "Movement Speed:": "Velocità di movimento:",
    "Speed:": "Velocità:",
    "Spell Haste:": "Celerità magica:",
    "Critical Chance:": "Probabilità di critico:",
    "Critical Damage:": "Danno critico:",
    "Armor:": "Armatura:",
    "Armor Percent:": "Armatura %:",
    "Armor Penetration:": "Penetrazione dell'armatura:",
    "Resistance:": "Resistenza:",
    "Resistance Percent:": "Resistenza %:",
    "Physical": "Fisico",
    "Physical Damage:": "Danno fisico:",
    "Physical Piercing:": "Penetrazione fisica:",
    "Piercing": "Penetrazione",
    "Magic Damage:": "Danno magico:",
    "Magic Piercing:": "Penetrazione magica:",
    "Blunt Armor:": "Armatura contundente:",
    "Blunt Damage:": "Danno contundente:",
    "Blunt Piercing:": "Penetrazione contundente:",
    "Strike Armor:": "Armatura da taglio:",
    "Strike Damage:": "Danno da taglio:",
    "Strike Piercing:": "Penetrazione da taglio:",
    "Thrust Armor:": "Armatura perforante:",
    "Thrust Damage:": "Danno perforante:",
    "Thrust Piercing:": "Penetrazione perforante:",
    "Fire": "Fuoco",
    "Fire Damage:": "Danno da fuoco:",
    "Fire Piercing:": "Penetrazione da fuoco:",
    "Fire Resistance:": "Resistenza al fuoco:",
    "Ice Damage:": "Danno da ghiaccio:",
    "Ice Piercing:": "Penetrazione da ghiaccio:",
    "Ice Resistance:": "Resistenza al ghiaccio:",
    "Ether Damage:": "Danno da etere:",
    "Ether Piercing:": "Penetrazione da etere:",
    "Ether Resistance:": "Resistenza all'etere:",
    "Decay Damage:": "Danno da decadimento:",
    "Decay Piercing:": "Penetrazione da decadimento:",
    "Decay Resistance:": "Resistenza al decadimento:",
    "Electricity Damage:": "Danno da elettricità:",
    "Poison Damage:": "Danno da veleno:",
    "Poison Duration:": "Durata veleno:",
    "Bleeding Damage:": "Danno da sanguinamento:",
    "Bleeding Duration:": "Durata sanguinamento:",
    "Burning Duration:": "Durata ustione:",
    "Chill Duration:": "Durata gelo:",
    "Chill Power:": "Potenza del gelo:",
    "Rage Duration:": "Durata furia:",
    "Max Bleeding:": "Sanguinamento max:",
    "Max Burning:": "Ustione max:",
    "Max Chill:": "Gelo max:",
    "Max Poison:": "Veleno max:",
    "Max Rage:": "Furia max:",
    "Max Shock:": "Scossa max:",
    "Max Drunkenness": "Ebbrezza max",
    "Damage vs. Bleeding:": "Danno vs. sanguinamento:",
    "Damage vs. Burning:": "Danno vs. ustione:",
    "Damage vs. Chilled:": "Danno vs. assiderato:",
    "Damage vs. Poison:": "Danno vs. veleno:",
    "Damage vs. Stunned:": "Danno vs. stordito:",
    "Damage vs. Piercing:": "Danno vs. penetrazione:",
    "Stun": "Stordimento",
    "Offence": "Offesa",
    "Offense": "Offesa",
    "Defence": "Difesa",
    "Defense": "Difesa",
    "Support": "Supporto",
    "Utility": "Utilità",
    "Vitals": "Vitali",
    "Vitals & Utility": "Vitali e utilità",
    "Proficiency": "Competenza",
    "Combo Modifier": "Modificatore di combo",
    "Modifiers": "Modificatori",
    "Piece Bonus": "Bonus per pezzo",
    "Set Bonuses": "Bonus dei set",
    "Effect": "Effetto",
    "Status Effect": "Effetto di stato",
    "Status Effects": "Effetti di stato",
    "Invulnerability": "Invulnerabilità",
    "Untargetable": "Non bersagliabile",
    "No Cooldown": "Nessun tempo di recupero",
    "On Cooldown": "In recupero",
    "Well Rested": "Ben riposato",

    # ---- progressione ------------------------------------------------------
    "Level": "Livello",
    "Level:": "Livello:",
    "Level {0}": "Livello {0}",
    "Level {0} (Max)": "Livello {0} (Max)",
    "Max Level": "Livello massimo",
    "Max Level:": "Livello massimo:",
    "Current XP:": "XP attuali:",
    "Max XP:": "XP massimi:",
    "Next Level XP:": "XP prossimo livello:",
    "Party XP:": "XP del gruppo:",
    "Received XP:": "XP ricevuti:",
    "+{0} XP": "+{0} XP",
    "XP increased": "XP aumentati",
    "1 point": "1 punto",
    "Available Skillpoint": "Punto abilità disponibile",
    "Your current level.": "Il tuo livello attuale.",
    "{0} is now level {1}": "{0} è ora di livello {1}",

    # ---- equipaggiamento e oggetti ----------------------------------------
    "Item": "Oggetto",
    "Item:": "Oggetto:",
    "Item Menu": "Menu oggetti",
    "Item menu": "Menu oggetti",
    "Item Slot 1": "Slot oggetto 1",
    "Item Slot 2": "Slot oggetto 2",
    "Item Slot 3": "Slot oggetto 3",
    "Item Slot 4": "Slot oggetto 4",
    "New item:": "Nuovo oggetto:",
    "Received item:": "Oggetto ricevuto:",
    "Choose item": "Scegli oggetto",
    "Equipment": "Equipaggiamento",
    "Equipment panel": "Pannello equipaggiamento",
    "Equipment Sets": "Set di equipaggiamento",
    "Shatter Equipment": "Frantuma equipaggiamento",
    "Gear": "Attrezzatura",
    "Tools": "Strumenti",
    "Combat Item": "Oggetto da combattimento",
    "Consumable": "Consumabile",
    "Container": "Contenitore",
    "Private container": "Contenitore privato",
    "Public container": "Contenitore pubblico",
    "Chest": "Cassa",
    "Chest List": "Elenco delle casse",
    "Chest Type": "Tipo di cassa",
    "No chests supplying": "Nessuna cassa che rifornisce",
    "Pulling from 1 chest": "Prelievo da 1 cassa",
    "Storage": "Deposito",
    "No Space": "Spazio insufficiente",
    "Boots": "Stivali",
    "Gloves": "Guanti",
    "Pants": "Pantaloni",
    "Cape": "Mantello",
    "Scarf": "Sciarpa",
    "Brooch": "Spilla",
    "Shoulder Pad": "Spallaccio",
    "Clothing": "Abbigliamento",
    "Clothing 1": "Abbigliamento 1",
    "Clothing 2": "Abbigliamento 2",
    "Fur": "Pelliccia",
    "Blade": "Lama",
    "Sword": "Spada",
    "Axe": "Ascia",
    "Axe 1": "Ascia 1",
    "Axe 2": "Ascia 2",
    "Battle Axe": "Ascia da battaglia",
    "Dagger 1": "Pugnale 1",
    "Dagger 2": "Pugnale 2",
    "Twin Daggers": "Pugnali gemelli",
    "Crossbow": "Balestra",
    "Pickaxe": "Piccone",
    "Shovel": "Pala",
    "Fishing Rod": "Canna da pesca",
    "Cutting Shears": "Cesoie",
    "Cooked Beast Meat": "Carne di bestia cotta",
    "Waygate Scroll": "Pergamena del Varco",
    "Map Fragment": "Frammento di mappa",
    "Rarity": "Rarità",
    "Common": "Comune",
    "Uncommon": "Non comune",
    "Rare": "Raro",
    "Ancient": "Antico",
    "Mythical": "Mitico",
    "Regular": "Normale",
    "Owned: {0}": "Posseduti: {0}",
    "Select Quantity": "Seleziona la quantità",
    "Incorrect Quantity": "Quantità errata",
    "Potential Loot": "Bottino possibile",
    "Personal Loot": "Bottino personale",
    "Personal loot": "Bottino personale",
    "Personal\\nLoot": "Bottino\\npersonale",

    # ---- costruzione e artigianato ----------------------------------------
    "Build": "Costruisci",
    "Building Name": "Nome della costruzione",
    "Building Upgrade": "Miglioramento della costruzione",
    "Choose Building": "Scegli la costruzione",
    "Structures": "Strutture",
    "Foundation": "Fondazione",
    "Walls": "Muri",
    "Wall Decor": "Decorazioni da muro",
    "Roofs": "Tetti",
    "Fences": "Recinti",
    "Furniture": "Mobilio",
    "Decor": "Decorazioni",
    "Ground Cover": "Copertura del terreno",
    "Ground Decor": "Decorazioni del terreno",
    "Bed": "Letto",
    "Campfire": "Falò",
    "Campfire Required": "Richiede un falò",
    "Woodfire Stove": "Stufa a legna",
    "Workbench": "Banco da lavoro",
    "Workbenches": "Banchi da lavoro",
    "Workbench Required": "Richiede un banco da lavoro",
    "Require Workstation": "Richiede una postazione",
    "Alchemy Bench": "Banco d'alchimia",
    "Alchemy Table": "Tavolo d'alchimia",
    "Cooking Station": "Postazione di cucina",
    "Forge": "Fucina",
    "Pet Pen": "Recinto dei compagni",
    "Pet Pen Level": "Livello del recinto",
    "Crafting": "Artigianato",
    "Crafting Codex": "Codex dell'artigianato",
    "Recipe": "Ricetta",
    "Recipes": "Ricette",
    "Recipe Name": "Nome della ricetta",
    "Choose Recipe": "Scegli la ricetta",
    "Choose recipe": "Scegli la ricetta",
    "Connected Recipes": "Ricette collegate",
    "New Recipe Unlocked": "Nuova ricetta sbloccata",
    "Ingredients": "Ingredienti",
    "Required Materials": "Materiali richiesti",
    "Required:": "Richiesti:",
    "Requires: {0}": "Richiede: {0}",
    "Used In": "Usato in",
    "Output": "Risultato",
    "output": "risultato",
    "Production": "Produzione",
    "Cost": "Costo",
    "Farming": "Agricoltura",
    "Crops grew": "Le colture sono cresciute",
    "{0} ready to harvest": "{0} pronto per il raccolto",
    "{0} still growing": "{0} è ancora in crescita",

    # ---- mondo, mappa, missioni -------------------------------------------
    "World": "Mondo",
    "Your World": "Il tuo mondo",
    "NewWorld": "NuovoMondo",
    "Enter World Name": "Inserisci il nome del mondo",
    "world name required": "nome del mondo obbligatorio",
    "World Options": "Opzioni del mondo",
    "World Difficulty": "Difficoltà del mondo",
    "Singleplayer": "Giocatore singolo",
    "Singleplayer World": "Mondo per giocatore singolo",
    "Multiplayer": "Multigiocatore",
    "Multiplayer World": "Mondo multigiocatore",
    "Current Area": "Area attuale",
    "Markers": "Segnalini",
    "POIs": "Punti d'interesse",
    "Map Revealed": "Mappa rivelata",
    "Show Beacon Arrows": "Mostra le frecce dei segnalatori",
    "Quest": "Missione",
    "Quest Arrows": "Frecce delle missioni",
    "Quest Complete!": "Missione completata!",
    "Quest Update": "Aggiornamento della missione",
    "Main Quest": "Missione principale",
    "Main Quests": "Missioni principali",
    "Side Quest": "Missione secondaria",
    "Side Quests": "Missioni secondarie",
    "NPC Quests": "Missioni degli NPC",
    "New Main Quest:": "Nuova missione principale:",
    "New Side Quest:": "Nuova missione secondaria:",
    "Show Quest Arrows": "Mostra le frecce delle missioni",
    "Show Quest Tracker": "Mostra il tracciatore missioni",
    "Show Tracked Quest": "Mostra la missione seguita",
    "Auto Show Next Quest": "Mostra automaticamente la prossima",
    "Objective:": "Obiettivo:",
    "Rewards": "Ricompense",
    "Received Gold:": "Oro ricevuto:",
    "Received Followers:": "Seguaci ricevuti:",
    "Deed": "Incarico",
    "Deeds": "Incarichi",
    "Available Deeds": "Incarichi disponibili",
    "Choose Deed": "Scegli l'incarico",
    "New Deed:": "Nuovo incarico:",
    "Deed level": "Livello dell'incarico",
    "Deed level:": "Livello dell'incarico:",
    "Adjust Deed Level": "Regola il livello dell'incarico",
    "Bounties": "Taglie",
    "Available Bounties": "Taglie disponibili",
    "TURN IN": "CONSEGNA",
    "IN PROGRESS": "IN CORSO",
    "Completed": "Completato",
    "Page Complete": "Pagina completata",
    "Journal": "Diario",
    "Codex": "Codex",
    "Exploration": "Esplorazione",
    "Adventure": "Avventura",
    "Adventure:": "Avventura:",
    "Events": "Eventi",
    "Nearby Event:": "Evento vicino:",
    "Encounters reset": "Scontri azzerati",
    "Monsters reappear": "I mostri ricompaiono",
    "Boss": "Boss",
    "Leads to the": "Conduce a",

    # ---- luoghi ------------------------------------------------------------
    "Sanctum": "Santuario",
    "Lost Caverns": "Caverne Perdute",
    "Southbarrows": "Southbarrows",
    "Earlwood Bridge": "Ponte di Earlwood",
    "Briar Heart Bridge": "Ponte di Briar Heart",
    "Basilton's Farm": "Fattoria di Basilton",
    "Manga's Forge": "Fucina di Manga",
    "Myrll's Shop": "Negozio di Myrll",
    "Heimen's Shop": "Negozio di Heimen",
    "Heimen's Music Box": "Carillon di Heimen",
    "Saqi's Kitchen": "Cucina di Saqi",
    "Myrll Required": "Richiede Myrll",
    "Rahaner Required": "Richiede Rahaner",
    "Tamsin Required": "Richiede Tamsin",
    "Welcome to Dimraeth!": "Benvenuto a Dimraeth!",

    # ---- personaggio -------------------------------------------------------
    "Character": "Personaggio",
    "Your Character": "Il tuo personaggio",
    "Character Info": "Informazioni sul personaggio",
    "Character View": "Vista del personaggio",
    "With Character": "Con il personaggio",
    "Enter Character Name": "Inserisci il nome del personaggio",
    "New Character Only": "Solo nuovi personaggi",
    "New Characters Only": "Solo nuovi personaggi",
    "New characters only": "solo nuovi personaggi",
    "Played Before": "Già giocato",
    "Race": "Razza",
    "Race:": "Razza:",
    "Human": "Umano",
    "Elf": "Elfo",
    "Class": "Classe",
    "Class:": "Classe:",
    "Archetype": "Archetipo",
    "Archetype:": "Archetipo:",
    "Archetype\\n": "Archetipo\\n",
    "Persona": "Personalità",
    "Gender": "Genere",
    "Skin": "Pelle",
    "Horns": "Corna",
    "Brawler": "Rissoso",
    "Magician": "Mago",
    "Scout": "Esploratore",
    "Heroic": "Eroico",
    "Joker": "Burlone",
    "Scholar": "Studioso",
    "Stoic": "Stoico",
    "Courier": "Corriere",
    "Courier Overview:": "Riepilogo del corriere:",
    "Trainer": "Addestratore",
    "Hunter": "Cacciatore",
    "HornedVanguard": "AvanguardiaCornuta",

    # ---- magie e abilità ---------------------------------------------------
    "Spell": "Incantesimo",
    "Spell 1": "Incantesimo 1",
    "Spell 2": "Incantesimo 2",
    "Spell 3": "Incantesimo 3",
    "Spell 4": "Incantesimo 4",
    "Spell 5": "Incantesimo 5",
    "All Spells": "Tutti gli incantesimi",
    "Defensive Spell": "Incantesimo difensivo",
    "Pet Spell": "Incantesimo del compagno",
    "Pet Spell Name": "Nome dell'incantesimo del compagno",
    "Cast spells with:": "Lancia gli incantesimi con:",
    "Hold Cast": "Mantieni il lancio",
    "Passive": "Passiva",
    "Earth": "Terra",
    "Frost": "Gelo",
    "Shadow": "Ombra",
    "Shadow Arts": "Arti dell'ombra",
    "Time Magic": "Magia del tempo",
    "Plague Magic": "Magia della peste",
    "Boulder Toss": "Lancio di masso",
    "Frost Javelin": "Giavellotto gelido",
    "Tyrant Quake": "Sisma del Tiranno",
    "Cornu charge": "Carica di Cornu",
    "Cornu Charge\\n": "Carica di Cornu\\n",
    "Earthshaker\\n": "Scuotiterra\\n",
    "Elemental Ranger\\n": "Ranger Elementale\\n",
    "Drain Sustenance\\n": "Prosciuga sostentamento\\n",
    "Back\\n": "Indietro\\n",

    # ---- compagni ----------------------------------------------------------
    "Pet": "Compagno",
    "Pet Menu": "Menu dei compagni",
    "Pet Description": "Descrizione del compagno",
    "Pet courier": "Corriere compagno",
    "Dog": "Cane",

    # ---- gruppo e multigiocatore -------------------------------------------
    "Party": "Gruppo",
    "Current Party": "Gruppo attuale",
    "Party Invitation": "Invito al gruppo",
    "Show Party Arrows": "Mostra le frecce del gruppo",
    "Show Party HUD": "Mostra l'HUD del gruppo",
    "Player": "Giocatore",
    "players": "giocatori",
    "Player List": "Elenco dei giocatori",
    "Player Benchmark": "Test prestazioni",
    "Max Players": "Giocatori massimi",
    "Adjust Player Limit": "Regola il limite dei giocatori",
    "Banned Players: {0}": "Giocatori banditi: {0}",
    "Total Banned Players": "Giocatori banditi in totale",
    "Host": "Ospite",
    "Server": "Server",
    "Select a server": "Seleziona un server",
    "Selected Server": "Server selezionato",
    "enter server name": "inserisci il nome del server",
    "Empty Servers": "Server vuoti",
    "Full Servers": "Server pieni",
    "No servers online": "Nessun server online",
    "Server went offline": "Il server è andato offline",
    "Server lobby is full": "La lobby del server è piena",
    "No lobbies found.": "Nessuna lobby trovata.",
    "Lobby Options": "Opzioni della lobby",
    "Lobby Type": "Tipo di lobby",
    "Adjust Lobby Number": "Regola il numero della lobby",
    "Public": "Pubblica",
    "Private": "Privata",
    "Invite-Only": "Solo su invito",
    "Friends Only": "Solo amici",
    "With Friends": "Con gli amici",
    "Friends Online": "Amici online",
    "No friends online": "Nessun amico online",
    "Password": "Password",
    "Enter Password": "Inserisci la password",
    "Password Protected": "Protetta da password",
    "Password protected": "protetta da password",
    "Incorrect password": "Password errata",
    "Enter Code...": "Inserisci il codice...",
    "Unknown host": "Ospite sconosciuto",
    "Friendly Fire": "Fuoco amico",
    "Friendly fire": "fuoco amico",
    "Enable Chat": "Attiva la chat",
    "Show Chat": "Mostra la chat",
    "Emote": "Espressione",
    "Emotes": "Espressioni",
    "Emoji Wheel": "Ruota delle emoji",
    "{0} has disconnected": "{0} si è disconnesso",
    "{0} has killed {1}": "{0} ha ucciso {1}",
    "{0} is reserved": "{0} è riservato",
    "Empty Seat": "Posto libero",

    # ---- poker (termini non ambigui) --------------------------------------
    "Ace": "Asso",
    "King": "Re",
    "Queen": "Donna",
    "Jack": "Fante",
    "Ten": "Dieci",
    "Nine": "Nove",
    "Eight": "Otto",
    "Seven": "Sette",
    "Six": "Sei",
    "Five": "Cinque",
    "Four": "Quattro",
    "Three": "Tre",
    "Two": "Due",
    "Fold": "Passa",
    "Call ${0}": "Chiama ${0}",
    "Bet ${0}": "Punta ${0}",
    "Raise ${0}": "Rilancia ${0}",
    "Hand Rankings": "Punteggi delle mani",
    "Unknown Hand": "Mano sconosciuta",
    "Betting Basics": "Basi della puntata",
    "How To Play": "Come si gioca",
    "One Away": "Manca uno",
    "One Away!": "Manca uno!",
    "The table is full.": "Il tavolo è pieno.",
    "Starting a new hand.": "Inizio di una nuova mano.",
    "{0} bet {1} chips.": "{0} ha puntato {1} fiche.",
    "{0} called.": "{0} ha chiamato.",
    "{0} checked.": "{0} ha passato.",
    "{0} folded.": "{0} si è ritirato.",
    "{0} sat out.": "{0} salta il turno.",
    "{0} sat back in.": "{0} è rientrato.",
    "(Best to Least)": "(Dal migliore al peggiore)",

    # ---- impostazioni ------------------------------------------------------
    "Settings": "Impostazioni",
    "Options": "Opzioni",
    "General": "Generale",
    "Audio": "Audio",
    "Audio Settings": "Impostazioni audio",
    "Display": "Schermo",
    "Display Settings": "Impostazioni dello schermo",
    "Control": "Comandi",
    "Control Settings": "Impostazioni dei comandi",
    "Control Type": "Tipo di comando",
    "Gameplay Settings": "Impostazioni di gioco",
    "Language": "Lingua",
    "Language Selection": "Selezione della lingua",
    "Master Volume": "Volume principale",
    "Music": "Musica",
    "Music Volume": "Volume della musica",
    "SFX Volume": "Volume degli effetti",
    "Ambience Volume": "Volume dell'ambiente",
    "Resolution": "Risoluzione",
    "Frame Rate": "Frequenza dei fotogrammi",
    "Frames": "Fotogrammi",
    "VSync": "VSync",
    "Post Processing": "Post-elaborazione",
    "Shadow Quality": "Qualità delle ombre",
    "QualityPreset": "PresetQualità",
    "UI Scaling": "Scala dell'interfaccia",
    "Reduce Motion": "Riduci il movimento",
    "Show Mouse Direction": "Mostra la direzione del mouse",
    "Automatic Sprint": "Scatto automatico",
    "Normal Sprint": "Scatto normale",
    "Dash / Sprint": "Scatto / Corsa",
    "Environment Movement": "Movimento dell'ambiente",
    "Auto-Hide Base Walls": "Nascondi automaticamente i muri",
    "Hide Walls Off": "Non nascondere i muri",
    "Legacy Camera (Dev)": "Telecamera classica (Dev)",
    "Dynamic (Native)": "Dinamica (nativa)",
    "Developer Mode": "Modalità sviluppatore",
    "Auto": "Automatico",
    "Advanced": "Avanzate",
    "Low": "Basso",
    "Medium": "Medio",
    "High": "Alto",
    "Light": "Chiaro",
    "In game": "In gioco",
    "In menu": "Nel menu",
    "In-Game Menu": "Menu di gioco",
    "Main Menu": "Menu principale",
    "Input": "Input",
    "Enter Key...": "Premi un tasto...",
    "SHIFT": "MAIUSC",
    "Shift +": "Maiusc +",
    "SPACE": "SPAZIO",
    "space": "spazio",
    "Spacebar": "Barra spaziatrice",
    "Tab": "Tab",

    # ---- difficoltà --------------------------------------------------------
    "Difficulty": "Difficoltà",
    "Difficulty:": "Difficoltà:",
    "Difficulty Level": "Livello di difficoltà",
    "Adjust Difficulty": "Regola la difficoltà",
    "Easy": "Facile",
    "Hard": "Difficile",
    "Hardcore": "Hardcore",

    # ---- tempo -------------------------------------------------------------
    "Day": "Giorno",
    "Days": "Giorni",
    "Days:": "Giorni:",
    "Year": "Anno",
    "Years": "Anni",
    "Hour:": "Ora:",
    "Time": "Tempo",
    "Date": "Data",
    "Age: Unknown": "Età: sconosciuta",
    "10h left": "10h rimanenti",
    "A new day awakens...": "Un nuovo giorno si risveglia...",
    "You rested": "Ti sei riposato",
    "Weather:": "Meteo:",

    # ---- varie -------------------------------------------------------------
    "Name": "Nome",
    "Name:": "Nome:",
    "Title": "Titolo",
    "Type": "Tipo",
    "TYPE": "TIPO",
    "Types": "Tipi",
    "Category": "Categoria",
    "Details": "Dettagli",
    "Overview": "Riepilogo",
    "Header": "Intestazione",
    "Note": "Nota",
    "Note:": "Nota:",
    "Tips": "Suggerimenti",
    "Region": "Regione",
    "Set": "Set",
    "New": "Nuovo",
    "All": "Tutti",
    "Active": "Attivo",
    "active": "attivo",
    "inactive": "inattivo",
    "Locked": "Bloccato",
    "Unknown": "Sconosciuto",
    "Loading...": "Caricamento...",
    "queue": "coda",
    "Combat": "Combattimento",
    "Adjust Materials": "Regola i materiali",
    "Adjust Value": "Regola il valore",
    "Change Party Name": "Cambia il nome del gruppo",
    "Credit": "Crediti",
    "News & Updates": "Notizie e aggiornamenti",
    "Wishlist": "Lista dei desideri",
    "Social": "Sociale",
    "Gold:": "Oro:",
    "Memory": "Memoria",
    "Mem": "Mem",
    "Nourishment Low": "Nutrimento basso",
    "Nourishment drained": "Nutrimento esaurito",
    "Fill Sustenance": "Riempi il sostentamento",
    "Fill Vitals": "Riempi i vitali",
    "{0} refilled": "{0} ricaricato",
    "{0} reset": "{0} azzerato",
    "{0} returned": "{0} restituito",
    "{0} {1}/sec": "{0} {1}/sec",
    "Facility Upgraded": "Struttura migliorata",
    "Waygate Menu": "Menu dei Varchi",
    "Waygate:": "Varco:",
    "Shop": "Negozio",
}
